# Merge wa.* translation namespace into all locale files.
# Idempotent: removes existing "wa": {...} block (top-level) before inserting fresh.

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$localesDir = Join-Path $root 'locales'
$enc = [System.Text.UTF8Encoding]::new($false)

function Build-WaBlock {
  param([hashtable]$wa)
  return ($wa | ConvertTo-Json -Depth 12)
}

function Remove-ExistingWa {
  param([string]$text)
  # Find the "wa": { occurrence and remove balanced block + leading comma.
  $idx = $text.IndexOf('"wa":')
  if ($idx -lt 0) { return $text }
  # Find opening brace
  $openIdx = $text.IndexOf('{', $idx)
  if ($openIdx -lt 0) { return $text }
  $depth = 0
  $i = $openIdx
  while ($i -lt $text.Length) {
    $c = $text[$i]
    if ($c -eq '{') { $depth++ }
    elseif ($c -eq '}') {
      $depth--
      if ($depth -eq 0) { break }
    }
    $i++
  }
  if ($depth -ne 0) { return $text }
  $endIdx = $i  # index of matching closing brace
  # Walk back from $idx to find leading comma
  $startIdx = $idx
  $j = $idx - 1
  while ($j -ge 0 -and ($text[$j] -eq ' ' -or $text[$j] -eq "`r" -or $text[$j] -eq "`n" -or $text[$j] -eq "`t")) { $j-- }
  if ($j -ge 0 -and $text[$j] -eq ',') { $startIdx = $j }
  return $text.Substring(0, $startIdx) + $text.Substring($endIdx + 1)
}

function Insert-Wa {
  param([string]$text, [string]$waJson)
  # waJson is a full {...} object. Insert as last property of root object.
  $lastBrace = $text.LastIndexOf('}')
  if ($lastBrace -lt 0) { throw 'No closing brace found' }
  # Walk back from $lastBrace to find last non-whitespace char
  $j = $lastBrace - 1
  while ($j -ge 0 -and ($text[$j] -eq ' ' -or $text[$j] -eq "`r" -or $text[$j] -eq "`n" -or $text[$j] -eq "`t")) { $j-- }
  $needsComma = $true
  if ($j -ge 0 -and ($text[$j] -eq '{' -or $text[$j] -eq ',')) { $needsComma = $false }
  $sep = if ($needsComma) { ",`r`n  " } else { "`r`n  " }
  # Strip outer braces from waJson and indent
  $inner = $waJson.Trim()
  if ($inner.StartsWith('{')) { $inner = $inner.Substring(1) }
  if ($inner.EndsWith('}'))   { $inner = $inner.Substring(0, $inner.Length - 1) }
  $inner = $inner.Trim()
  $insert = $sep + '"wa": {' + "`r`n    " + $inner + "`r`n  }"
  return $text.Substring(0, $j + 1) + $insert + "`r`n" + $text.Substring($lastBrace)
}

# ============================================================
# TRANSLATION PACKS
# ============================================================

$packs = @{}

$packs['en.default'] = @{
  nav = @{ tools = 'Tools'; about = 'About'; request = 'Request'; contact = 'Contact' }
  cta = @{ get_a_tool = 'Get a tool'; browse_tools = 'Browse tools'; read_manifesto = 'Read the manifesto'; send_message = 'Send message'; send_request = 'Send request' }
  tagline = 'Built once. Yours forever.'
  language_label = 'Language'
  hero = @{ eyebrow = 'Weird Artist · est. 2026'; title_a = 'Software you buy.'; title_b = 'Once.'; subtitle = 'Weird Artist makes desktop tools for marketers, traders, and operators who refuse to rent their workflow.' }
  footer = @{ products = 'Products'; company = 'Company'; legal = 'Legal'; blurb = 'Pay-once desktop tools for people who actually do the work.'; upcoming = 'Upcoming · soon'; all_tools = 'All tools'; request_a_tool = 'Request a tool'; privacy = 'Privacy'; terms = 'Terms'; refund = 'Refund policy' }
  contact = @{ eyebrow = 'Talk to us'; title_a = 'Write us a'; title_b = 'letter.'; lede = 'One person reads every message and replies within two business days. No ticketing system. No first-line support bot. No "your call is important to us". Pick a channel below — or just send a tool request straight from the form.'; tab_message = 'Send a message'; tab_request = 'Request a tool'; message_intro = 'Refunds, partnerships, bug reports, or just to tell us we got the manifesto wrong — write in.'; request_intro = 'The roadmap is open. Tell us what you wish existed — what spreadsheet you keep duct-taping, what SaaS you keep cancelling and resubscribing to, what report you build by hand every Monday. If 10 people ask for the same thing, we will build it. If you are the only one and it is clever — we will build it anyway.'; success_title = 'Message received.'; success_body = 'You will hear back within two business days.'; request_success_title = 'Thanks. Got it.'; request_success_body = 'We read every request. If yours fits the workshop, you will hear back.'; error_title = "Couldn't send:"; direct_lines = 'Direct lines'; label_hello = 'Hello'; label_support = 'Support'; label_refund = 'Refund'; reply_window = 'Reply window'; reply_main = 'We answer Mon–Fri, within 2 business days. One real person, not a queue.'; reply_mute = 'For tool requests we read everything but only reply if we are building it or want clarification.' }
  form = @{ name = 'Your name'; email = 'Email'; subject = 'Subject'; message = 'Message'; category = 'Category'; request_what = 'What tool do you wish existed?'; subject_placeholder = 'Refund · partnership · bug · other'; request_placeholder = 'The shorter and weirder, the better.'; request_hint = 'No NDAs. No fluff. Just describe what would save you the most time.'; cat_crm = 'CRM & Marketing'; cat_finance = 'Finance & Trading'; cat_other = 'Productivity / Other' }
  about = @{ eyebrow = 'About · est. 2026'; title_a = 'Software you buy.'; title_b = 'Once.'; lede = 'Somewhere along the way software ate the world — and then started charging rent on the bite marks. Every workflow turned into a subscription. Every tool became a tenant in your bank account. Every operator, marketer and trader started paying $9, $29, $99 a month for the privilege of doing their own job. We think that is weird.' }
  privacy = @{ eyebrow = 'Legal · Privacy'; title_a = 'Your data stays'; title_b = 'on your disk.'; lede = 'Short version: our desktop tools do not phone home. We collect the bare minimum we need to sell you a license, send you a download link, and refund you if you ask. That is it.' }
  terms = @{ eyebrow = 'Legal · Terms'; title_a = 'Buy once. Yours'; title_b = 'forever.'; lede = 'Plain-English version: you pay once, you get a perpetual license to use the app on your machines, you keep what you bought even if we disappear. No subscription, no auto-renewal, no surprise lockouts. The longer version is below.' }
  refund = @{ eyebrow = 'Legal · Refund'; title_a = '30 days.'; title_b = 'No questions.'; lede = 'If the tool does not fit your workflow, does not do what the page promised, or you simply changed your mind — email us within 30 days of purchase and we will refund the full amount. No forms. No exit interview. No "are you sure?" popup.' }
  showcase = @{ eyebrow = 'Currently shipping' }
}

$packs['uk'] = @{
  nav = @{ tools = 'Інструменти'; about = 'Про нас'; request = 'Запит'; contact = 'Контакти' }
  cta = @{ get_a_tool = 'Купити інструмент'; browse_tools = 'Каталог'; read_manifesto = 'Маніфест'; send_message = 'Надіслати'; send_request = 'Надіслати запит' }
  tagline = 'Куплено раз. Назавжди твоє.'
  language_label = 'Мова'
  hero = @{ eyebrow = 'Weird Artist · засновано 2026'; title_a = 'Софт, який купуєш.'; title_b = 'Один раз.'; subtitle = 'Weird Artist робить десктоп-інструменти для маркетологів, трейдерів і операційників, які не хочуть орендувати власний робочий процес.' }
  footer = @{ products = 'Продукти'; company = 'Компанія'; legal = 'Правова інформація'; blurb = 'Pay-once десктоп-інструменти для тих, хто реально робить роботу.'; upcoming = 'Скоро · в розробці'; all_tools = 'Усі інструменти'; request_a_tool = 'Запит на інструмент'; privacy = 'Конфіденційність'; terms = 'Умови'; refund = 'Політика повернення' }
  contact = @{ eyebrow = 'Напиши нам'; title_a = 'Напиши нам'; title_b = 'лист.'; lede = 'Кожне повідомлення читає одна людина і відповідає протягом двох робочих днів. Жодних тікет-систем. Жодного бота першої лінії. Жодних «ваш дзвінок важливий для нас». Обери канал нижче — або одразу надішли запит на інструмент через форму.'; tab_message = 'Надіслати повідомлення'; tab_request = 'Запит на інструмент'; message_intro = 'Повернення, партнерство, баги, або просто сказати нам що ми написали маніфест неправильно — пиши.'; request_intro = 'Дорожня карта відкрита. Розкажи що ти хотів би побачити — яку таблицю ти постійно склеюєш скотчем, який SaaS ти постійно скасовуєш і знову підписуєш, який звіт ти кожного понеділка робиш руками. Якщо 10 людей попросять те саме — ми побудуємо. Якщо ти сам і це круто — теж побудуємо.'; success_title = 'Повідомлення отримано.'; success_body = 'Відповімо протягом двох робочих днів.'; request_success_title = 'Дякуємо. Прийняли.'; request_success_body = 'Ми читаємо кожен запит. Якщо твій підходить нашій майстерні — почуєш від нас.'; error_title = 'Не вдалося надіслати:'; direct_lines = 'Прямі контакти'; label_hello = 'Привіт'; label_support = 'Підтримка'; label_refund = 'Повернення'; reply_window = 'Час відповіді'; reply_main = 'Відповідаємо пн–пт, протягом 2 робочих днів. Одна жива людина, а не черга.'; reply_mute = 'Запити на інструменти ми читаємо всі, але відповідаємо лише якщо беремось будувати або потрібне уточнення.' }
  form = @{ name = "Твоє ім'я"; email = 'Email'; subject = 'Тема'; message = 'Повідомлення'; category = 'Категорія'; request_what = 'Який інструмент ти хотів би побачити?'; subject_placeholder = 'Повернення · партнерство · баг · інше'; request_placeholder = 'Чим коротше і дивніше — тим краще.'; request_hint = 'Без NDA. Без води. Просто опиши що зекономило б тобі найбільше часу.'; cat_crm = 'CRM і маркетинг'; cat_finance = 'Фінанси і трейдинг'; cat_other = 'Продуктивність / Інше' }
  about = @{ eyebrow = 'Про нас · засновано 2026'; title_a = 'Софт, який купуєш.'; title_b = 'Один раз.'; lede = 'Десь по дорозі софт зжер світ — а тоді почав брати оренду за сліди укусів. Кожен робочий процес перетворився на підписку. Кожен інструмент став орендарем у твоєму банківському рахунку. Кожен оператор, маркетолог і трейдер почав платити $9, $29, $99 на місяць за привілей робити свою власну роботу. Ми вважаємо що це дивно.' }
  privacy = @{ eyebrow = 'Правова · Приватність'; title_a = 'Твої дані залишаються'; title_b = 'на твоєму диску.'; lede = 'Коротко: наші десктоп-інструменти не дзвонять додому. Ми збираємо мінімум потрібний щоб продати тобі ліцензію, надіслати посилання на завантаження і повернути гроші якщо попросиш. Все.' }
  terms = @{ eyebrow = 'Правова · Умови'; title_a = 'Купуєш раз. Твоє'; title_b = 'назавжди.'; lede = 'Простими словами: ти платиш один раз, отримуєш безстрокову ліцензію на використання застосунку на своїх машинах, лишаєшся з тим що купив навіть якщо ми зникнемо. Жодних підписок, жодного авто-продовження, жодних сюрпризних блокувань. Розширена версія нижче.' }
  refund = @{ eyebrow = 'Правова · Повернення'; title_a = '30 днів.'; title_b = 'Без питань.'; lede = 'Якщо інструмент не підійшов твоєму процесу, не робить того що обіцяла сторінка, або ти просто передумав — напиши нам протягом 30 днів від покупки і ми повернемо повну суму. Жодних форм. Жодного інтерв''ю. Жодного попапа «ти впевнений?».' }
  showcase = @{ eyebrow = 'Зараз у магазині' }
}

$packs['de'] = @{
  nav = @{ tools = 'Tools'; about = 'Über uns'; request = 'Anfrage'; contact = 'Kontakt' }
  cta = @{ get_a_tool = 'Tool holen'; browse_tools = 'Tools ansehen'; read_manifesto = 'Manifest lesen'; send_message = 'Nachricht senden'; send_request = 'Anfrage senden' }
  tagline = 'Einmal gekauft. Für immer dein.'
  language_label = 'Sprache'
  hero = @{ eyebrow = 'Weird Artist · gegründet 2026'; title_a = 'Software, die du kaufst.'; title_b = 'Einmal.'; subtitle = 'Weird Artist baut Desktop-Tools für Marketer, Trader und Operatoren, die ihren Workflow nicht mieten wollen.' }
  footer = @{ products = 'Produkte'; company = 'Unternehmen'; legal = 'Rechtliches'; blurb = 'Pay-once Desktop-Tools für Leute, die die Arbeit tatsächlich machen.'; upcoming = 'Bald verfügbar'; all_tools = 'Alle Tools'; request_a_tool = 'Tool anfragen'; privacy = 'Datenschutz'; terms = 'AGB'; refund = 'Rückgabe' }
  contact = @{ eyebrow = 'Sprich mit uns'; title_a = 'Schreib uns einen'; title_b = 'Brief.'; lede = 'Eine Person liest jede Nachricht und antwortet innerhalb von zwei Werktagen. Kein Ticketsystem. Kein First-Line-Bot. Kein „Ihr Anruf ist uns wichtig". Wähle einen Kanal unten — oder schick gleich eine Tool-Anfrage über das Formular.'; tab_message = 'Nachricht senden'; tab_request = 'Tool anfragen'; message_intro = 'Rückgaben, Partnerschaften, Bug Reports, oder einfach um uns zu sagen dass wir das Manifest falsch geschrieben haben — schreib rein.'; request_intro = 'Die Roadmap ist offen. Sag uns was du dir wünschst — welche Tabelle du ständig mit Klebeband zusammenhältst, welches SaaS du immer wieder kündigst und neu abonnierst, welchen Report du jeden Montag von Hand baust. Wenn 10 Leute dasselbe wollen, bauen wir es. Wenn du allein bist und es clever ist — bauen wir es trotzdem.'; success_title = 'Nachricht erhalten.'; success_body = 'Du hörst innerhalb von zwei Werktagen von uns.'; request_success_title = 'Danke. Angekommen.'; request_success_body = 'Wir lesen jede Anfrage. Wenn deine in die Werkstatt passt, hörst du von uns.'; error_title = 'Konnte nicht senden:'; direct_lines = 'Direkte Kanäle'; label_hello = 'Hallo'; label_support = 'Support'; label_refund = 'Rückgabe'; reply_window = 'Antwortzeit'; reply_main = 'Wir antworten Mo–Fr innerhalb von 2 Werktagen. Eine echte Person, keine Warteschlange.'; reply_mute = 'Tool-Anfragen lesen wir alle, antworten aber nur wenn wir bauen oder Rückfragen haben.' }
  form = @{ name = 'Dein Name'; email = 'E-Mail'; subject = 'Betreff'; message = 'Nachricht'; category = 'Kategorie'; request_what = 'Welches Tool wünschst du dir?'; subject_placeholder = 'Rückgabe · Partnerschaft · Bug · Sonstiges'; request_placeholder = 'Je kürzer und schräger, desto besser.'; request_hint = 'Keine NDAs. Kein Geschwafel. Beschreib einfach was dir am meisten Zeit sparen würde.'; cat_crm = 'CRM & Marketing'; cat_finance = 'Finance & Trading'; cat_other = 'Produktivität / Sonstiges' }
  about = @{ eyebrow = 'Über uns · gegründet 2026'; title_a = 'Software, die du kaufst.'; title_b = 'Einmal.'; lede = 'Irgendwann hat Software die Welt gefressen — und dann angefangen, Miete für die Bissstellen zu nehmen. Jeder Workflow wurde zum Abo. Jedes Tool wurde zum Mieter in deinem Bankkonto. Jeder Operator, Marketer und Trader zahlt jetzt 9, 29, 99 Euro im Monat für das Privileg, seinen eigenen Job zu machen. Wir finden das schräg.' }
  privacy = @{ eyebrow = 'Rechtliches · Datenschutz'; title_a = 'Deine Daten bleiben'; title_b = 'auf deiner Platte.'; lede = 'Kurzfassung: Unsere Desktop-Tools telefonieren nicht nach Hause. Wir sammeln das absolute Minimum, das wir brauchen um dir eine Lizenz zu verkaufen, dir den Download zu schicken und dir auf Wunsch dein Geld zurückzugeben. Mehr nicht.' }
  terms = @{ eyebrow = 'Rechtliches · AGB'; title_a = 'Einmal kaufen. Dir gehört''s'; title_b = 'für immer.'; lede = 'Klartext: Du zahlst einmal, bekommst eine unbefristete Lizenz für deine Maschinen, behältst was du gekauft hast — auch wenn wir verschwinden. Kein Abo, keine Auto-Verlängerung, keine Überraschungssperren. Lange Version unten.' }
  refund = @{ eyebrow = 'Rechtliches · Rückgabe'; title_a = '30 Tage.'; title_b = 'Keine Fragen.'; lede = 'Wenn das Tool nicht in deinen Workflow passt, nicht das macht was die Seite versprach, oder du es dir einfach anders überlegt hast — schreib uns innerhalb von 30 Tagen nach dem Kauf und wir erstatten den vollen Betrag. Keine Formulare. Kein Exit-Interview. Kein „Bist du sicher?"-Popup.' }
  showcase = @{ eyebrow = 'Aktuell verfügbar' }
}

$packs['fr'] = @{
  nav = @{ tools = 'Outils'; about = 'À propos'; request = 'Demande'; contact = 'Contact' }
  cta = @{ get_a_tool = 'Acheter un outil'; browse_tools = 'Voir les outils'; read_manifesto = 'Lire le manifeste'; send_message = 'Envoyer'; send_request = 'Envoyer la demande' }
  tagline = 'Acheté une fois. À toi pour toujours.'
  language_label = 'Langue'
  hero = @{ eyebrow = 'Weird Artist · fondé en 2026'; title_a = 'Le logiciel que tu achètes.'; title_b = 'Une fois.'; subtitle = 'Weird Artist crée des outils desktop pour les marketeurs, traders et opérateurs qui refusent de louer leur propre workflow.' }
  footer = @{ products = 'Produits'; company = 'Entreprise'; legal = 'Mentions légales'; blurb = 'Outils desktop achetés une fois pour les gens qui font réellement le travail.'; upcoming = 'Bientôt disponible'; all_tools = 'Tous les outils'; request_a_tool = 'Demander un outil'; privacy = 'Confidentialité'; terms = 'Conditions'; refund = 'Remboursement' }
  contact = @{ eyebrow = 'Parle-nous'; title_a = 'Écris-nous une'; title_b = 'lettre.'; lede = 'Une seule personne lit chaque message et répond sous deux jours ouvrés. Pas de système de tickets. Pas de bot de première ligne. Pas de « votre appel est important pour nous ». Choisis un canal ci-dessous — ou envoie directement une demande d''outil via le formulaire.'; tab_message = 'Envoyer un message'; tab_request = 'Demander un outil'; message_intro = 'Remboursements, partenariats, bugs, ou juste pour nous dire qu''on a écrit le manifeste de travers — écris-nous.'; request_intro = 'La roadmap est ouverte. Dis-nous ce que tu aimerais voir — quel tableur tu rafistoles sans cesse, quel SaaS tu désabonnes et réabonnes en boucle, quel rapport tu construis à la main chaque lundi. Si 10 personnes demandent la même chose, on le construit. Si tu es seul et que c''est malin — on le construit quand même.'; success_title = 'Message reçu.'; success_body = 'Tu auras une réponse sous deux jours ouvrés.'; request_success_title = 'Merci. Bien reçu.'; request_success_body = 'On lit chaque demande. Si la tienne entre dans l''atelier, on te répondra.'; error_title = 'Impossible d''envoyer :'; direct_lines = 'Lignes directes'; label_hello = 'Bonjour'; label_support = 'Support'; label_refund = 'Remboursement'; reply_window = 'Délai de réponse'; reply_main = 'On répond du lundi au vendredi sous 2 jours ouvrés. Une vraie personne, pas une file d''attente.'; reply_mute = 'On lit toutes les demandes d''outils mais on ne répond que si on construit ou si on a besoin de précisions.' }
  form = @{ name = 'Ton nom'; email = 'E-mail'; subject = 'Sujet'; message = 'Message'; category = 'Catégorie'; request_what = 'Quel outil aimerais-tu voir exister ?'; subject_placeholder = 'Remboursement · partenariat · bug · autre'; request_placeholder = 'Plus c''est court et bizarre, mieux c''est.'; request_hint = 'Pas de NDA. Pas de blabla. Décris juste ce qui te ferait gagner le plus de temps.'; cat_crm = 'CRM & Marketing'; cat_finance = 'Finance & Trading'; cat_other = 'Productivité / Autre' }
  about = @{ eyebrow = 'À propos · fondé en 2026'; title_a = 'Le logiciel que tu achètes.'; title_b = 'Une fois.'; lede = 'À un moment donné, le logiciel a dévoré le monde — et a ensuite commencé à louer ses propres morsures. Chaque workflow est devenu un abonnement. Chaque outil est devenu un locataire de ton compte bancaire. Chaque opérateur, marketeur et trader s''est mis à payer 9, 29, 99 € par mois pour le privilège de faire son propre boulot. On trouve ça bizarre.' }
  privacy = @{ eyebrow = 'Légal · Confidentialité'; title_a = 'Tes données restent'; title_b = 'sur ton disque.'; lede = 'Version courte : nos outils desktop ne téléphonent pas à la maison. Nous collectons le strict minimum nécessaire pour te vendre une licence, t''envoyer un lien de téléchargement et te rembourser si tu le demandes. C''est tout.' }
  terms = @{ eyebrow = 'Légal · Conditions'; title_a = 'Acheté une fois. À toi'; title_b = 'pour toujours.'; lede = 'En clair : tu paies une fois, tu reçois une licence perpétuelle pour utiliser l''appli sur tes machines, tu gardes ce que tu as acheté même si on disparaît. Pas d''abonnement, pas de renouvellement automatique, pas de blocages surprise. La version longue est ci-dessous.' }
  refund = @{ eyebrow = 'Légal · Remboursement'; title_a = '30 jours.'; title_b = 'Sans question.'; lede = 'Si l''outil ne convient pas à ton workflow, ne fait pas ce que la page promettait, ou tu as simplement changé d''avis — écris-nous dans les 30 jours suivant l''achat et nous rembourserons le montant total. Pas de formulaire. Pas d''entretien de sortie. Pas de popup « es-tu sûr ? ».' }
  showcase = @{ eyebrow = 'Actuellement disponibles' }
}

$packs['it'] = @{
  nav = @{ tools = 'Strumenti'; about = 'Chi siamo'; request = 'Richiesta'; contact = 'Contatti' }
  cta = @{ get_a_tool = 'Acquista uno strumento'; browse_tools = 'Vedi strumenti'; read_manifesto = 'Leggi il manifesto'; send_message = 'Invia'; send_request = 'Invia richiesta' }
  tagline = 'Comprato una volta. Tuo per sempre.'
  language_label = 'Lingua'
  hero = @{ eyebrow = 'Weird Artist · fondato nel 2026'; title_a = 'Software che compri.'; title_b = 'Una volta.'; subtitle = 'Weird Artist crea strumenti desktop per marketer, trader e operatori che si rifiutano di affittare il proprio workflow.' }
  footer = @{ products = 'Prodotti'; company = 'Azienda'; legal = 'Legale'; blurb = 'Strumenti desktop a pagamento unico per chi fa davvero il lavoro.'; upcoming = 'In arrivo'; all_tools = 'Tutti gli strumenti'; request_a_tool = 'Richiedi uno strumento'; privacy = 'Privacy'; terms = 'Termini'; refund = 'Rimborso' }
  contact = @{ eyebrow = 'Parlaci'; title_a = 'Scrivici una'; title_b = 'lettera.'; lede = 'Una sola persona legge ogni messaggio e risponde entro due giorni lavorativi. Niente sistema di ticket. Niente bot di primo livello. Niente « la tua chiamata è importante per noi ». Scegli un canale qui sotto — o invia direttamente una richiesta di strumento dal form.'; tab_message = 'Invia un messaggio'; tab_request = 'Richiedi uno strumento'; message_intro = 'Rimborsi, partnership, bug report, o solo per dirci che abbiamo scritto il manifesto male — scrivici.'; request_intro = 'La roadmap è aperta. Dicci cosa vorresti vedere — che foglio Excel rappezzi continuamente, che SaaS continui a disdire e riabbonare, che report costruisci a mano ogni lunedì. Se 10 persone chiedono la stessa cosa, la costruiamo. Se sei solo e l''idea è geniale — la costruiamo lo stesso.'; success_title = 'Messaggio ricevuto.'; success_body = 'Ti risponderemo entro due giorni lavorativi.'; request_success_title = 'Grazie. Ricevuto.'; request_success_body = 'Leggiamo ogni richiesta. Se la tua entra nel laboratorio, ti risponderemo.'; error_title = 'Non è stato possibile inviare:'; direct_lines = 'Contatti diretti'; label_hello = 'Ciao'; label_support = 'Supporto'; label_refund = 'Rimborso'; reply_window = 'Tempi di risposta'; reply_main = 'Rispondiamo lun–ven entro 2 giorni lavorativi. Una persona reale, non una coda.'; reply_mute = 'Le richieste di strumenti le leggiamo tutte, ma rispondiamo solo se la costruiamo o vogliamo chiarimenti.' }
  form = @{ name = 'Il tuo nome'; email = 'Email'; subject = 'Oggetto'; message = 'Messaggio'; category = 'Categoria'; request_what = 'Che strumento vorresti che esistesse?'; subject_placeholder = 'Rimborso · partnership · bug · altro'; request_placeholder = 'Più corto e strano è, meglio è.'; request_hint = 'Niente NDA. Niente fuffa. Descrivi cosa ti farebbe risparmiare più tempo.'; cat_crm = 'CRM & Marketing'; cat_finance = 'Finance & Trading'; cat_other = 'Produttività / Altro' }
  about = @{ eyebrow = 'Chi siamo · fondato nel 2026'; title_a = 'Software che compri.'; title_b = 'Una volta.'; lede = 'Da qualche parte lungo la strada il software ha mangiato il mondo — e poi ha iniziato ad affittare i segni dei morsi. Ogni workflow è diventato un abbonamento. Ogni strumento è diventato un inquilino del tuo conto bancario. Ogni operatore, marketer e trader ha iniziato a pagare 9, 29, 99 € al mese per il privilegio di fare il proprio lavoro. Noi pensiamo sia strano.' }
  privacy = @{ eyebrow = 'Legale · Privacy'; title_a = 'I tuoi dati restano'; title_b = 'sul tuo disco.'; lede = 'Versione corta: i nostri strumenti desktop non chiamano a casa. Raccogliamo lo stretto necessario per venderti una licenza, mandarti il link di download e rimborsarti se lo chiedi. Tutto qui.' }
  terms = @{ eyebrow = 'Legale · Termini'; title_a = 'Compri una volta. Tuo'; title_b = 'per sempre.'; lede = 'In parole semplici: paghi una volta, ricevi una licenza perpetua per usare l''app sulle tue macchine, mantieni ciò che hai comprato anche se spariamo. Nessun abbonamento, nessun rinnovo automatico, nessun blocco a sorpresa. La versione lunga sotto.' }
  refund = @{ eyebrow = 'Legale · Rimborso'; title_a = '30 giorni.'; title_b = 'Senza domande.'; lede = 'Se lo strumento non si adatta al tuo workflow, non fa ciò che la pagina prometteva, o hai semplicemente cambiato idea — scrivici entro 30 giorni dall''acquisto e rimborsiamo l''intera cifra. Niente moduli. Niente exit interview. Niente popup « sei sicuro? ».' }
  showcase = @{ eyebrow = 'Attualmente disponibili' }
}

$packs['pl'] = @{
  nav = @{ tools = 'Narzędzia'; about = 'O nas'; request = 'Zapytanie'; contact = 'Kontakt' }
  cta = @{ get_a_tool = 'Kup narzędzie'; browse_tools = 'Zobacz narzędzia'; read_manifesto = 'Przeczytaj manifest'; send_message = 'Wyślij'; send_request = 'Wyślij zapytanie' }
  tagline = 'Kupione raz. Twoje na zawsze.'
  language_label = 'Język'
  hero = @{ eyebrow = 'Weird Artist · założone 2026'; title_a = 'Software, który kupujesz.'; title_b = 'Raz.'; subtitle = 'Weird Artist tworzy narzędzia desktopowe dla marketerów, traderów i operatorów, którzy odmawiają wynajmowania własnego workflow.' }
  footer = @{ products = 'Produkty'; company = 'Firma'; legal = 'Prawne'; blurb = 'Pay-once narzędzia desktopowe dla ludzi, którzy faktycznie wykonują pracę.'; upcoming = 'Wkrótce'; all_tools = 'Wszystkie narzędzia'; request_a_tool = 'Zapytanie o narzędzie'; privacy = 'Prywatność'; terms = 'Regulamin'; refund = 'Zwroty' }
  contact = @{ eyebrow = 'Napisz do nas'; title_a = 'Napisz nam'; title_b = 'list.'; lede = 'Każdą wiadomość czyta jedna osoba i odpowiada w ciągu dwóch dni roboczych. Żadnego systemu zgłoszeń. Żadnego bota pierwszej linii. Żadnego „twoja sprawa jest dla nas ważna". Wybierz kanał poniżej — albo wyślij zapytanie o narzędzie bezpośrednio z formularza.'; tab_message = 'Wyślij wiadomość'; tab_request = 'Zapytaj o narzędzie'; message_intro = 'Zwroty, partnerstwa, bugi, albo żeby nam powiedzieć, że napisaliśmy manifest źle — pisz.'; request_intro = 'Roadmapa jest otwarta. Powiedz nam co chciałbyś zobaczyć — jaki arkusz wciąż łatasz taśmą klejącą, jaki SaaS wciąż anulujesz i odnawiasz, jaki raport robisz ręcznie w każdy poniedziałek. Jeśli 10 osób poprosi o to samo — zbudujemy. Jeśli jesteś sam i to sprytne — i tak zbudujemy.'; success_title = 'Wiadomość otrzymana.'; success_body = 'Odezwiemy się w ciągu dwóch dni roboczych.'; request_success_title = 'Dzięki. Mamy.'; request_success_body = 'Czytamy każde zapytanie. Jeśli twoje pasuje do warsztatu, odezwiemy się.'; error_title = 'Nie udało się wysłać:'; direct_lines = 'Bezpośrednie kanały'; label_hello = 'Cześć'; label_support = 'Wsparcie'; label_refund = 'Zwrot'; reply_window = 'Czas odpowiedzi'; reply_main = 'Odpowiadamy pn–pt w ciągu 2 dni roboczych. Jedna prawdziwa osoba, nie kolejka.'; reply_mute = 'Wszystkie zapytania o narzędzia czytamy, ale odpowiadamy tylko jeśli budujemy lub potrzebujemy wyjaśnień.' }
  form = @{ name = 'Twoje imię'; email = 'Email'; subject = 'Temat'; message = 'Wiadomość'; category = 'Kategoria'; request_what = 'Jakie narzędzie chciałbyś żeby istniało?'; subject_placeholder = 'Zwrot · partnerstwo · bug · inne'; request_placeholder = 'Im krócej i dziwniej, tym lepiej.'; request_hint = 'Bez NDA. Bez pustych słów. Opisz co zaoszczędziłoby ci najwięcej czasu.'; cat_crm = 'CRM i marketing'; cat_finance = 'Finanse i trading'; cat_other = 'Produktywność / Inne' }
  about = @{ eyebrow = 'O nas · założone 2026'; title_a = 'Software, który kupujesz.'; title_b = 'Raz.'; lede = 'Gdzieś po drodze software pożarł świat — a potem zaczął pobierać czynsz za ślady ugryzień. Każdy workflow zamienił się w subskrypcję. Każde narzędzie stało się lokatorem twojego konta bankowego. Każdy operator, marketer i trader zaczął płacić 9, 29, 99 € miesięcznie za przywilej wykonywania własnej pracy. Uważamy, że to dziwne.' }
  privacy = @{ eyebrow = 'Prawne · Prywatność'; title_a = 'Twoje dane zostają'; title_b = 'na twoim dysku.'; lede = 'Krótka wersja: nasze narzędzia desktopowe nie dzwonią do domu. Zbieramy minimum potrzebne by sprzedać ci licencję, wysłać link do pobrania i zwrócić pieniądze jeśli poprosisz. Tyle.' }
  terms = @{ eyebrow = 'Prawne · Regulamin'; title_a = 'Kupujesz raz. Twoje'; title_b = 'na zawsze.'; lede = 'Po ludzku: płacisz raz, dostajesz wieczystą licencję na używanie aplikacji na swoich maszynach, zostajesz z tym co kupiłeś nawet jeśli znikniemy. Bez subskrypcji, bez auto-przedłużania, bez niespodziewanych blokad. Dłuższa wersja niżej.' }
  refund = @{ eyebrow = 'Prawne · Zwrot'; title_a = '30 dni.'; title_b = 'Bez pytań.'; lede = 'Jeśli narzędzie nie pasuje do twojego workflow, nie robi tego co obiecała strona, albo po prostu zmieniłeś zdanie — napisz do nas w ciągu 30 dni od zakupu, a zwrócimy pełną kwotę. Żadnych formularzy. Żadnego exit interview. Żadnego popupa „czy na pewno?".' }
  showcase = @{ eyebrow = 'Aktualnie dostępne' }
}

$packs['cs'] = @{
  nav = @{ tools = 'Nástroje'; about = 'O nás'; request = 'Žádost'; contact = 'Kontakt' }
  cta = @{ get_a_tool = 'Koupit nástroj'; browse_tools = 'Procházet nástroje'; read_manifesto = 'Přečíst manifest'; send_message = 'Odeslat'; send_request = 'Odeslat žádost' }
  tagline = 'Jednou koupeno. Tvoje navždy.'
  language_label = 'Jazyk'
  hero = @{ eyebrow = 'Weird Artist · založeno 2026'; title_a = 'Software, který si koupíš.'; title_b = 'Jednou.'; subtitle = 'Weird Artist vytváří desktopové nástroje pro markeťáky, tradery a operátory, kteří odmítají pronajímat si vlastní workflow.' }
  footer = @{ products = 'Produkty'; company = 'Firma'; legal = 'Právní'; blurb = 'Pay-once desktopové nástroje pro lidi, kteří práci skutečně dělají.'; upcoming = 'Brzy k dispozici'; all_tools = 'Všechny nástroje'; request_a_tool = 'Vyžádat nástroj'; privacy = 'Soukromí'; terms = 'Podmínky'; refund = 'Vrácení' }
  contact = @{ eyebrow = 'Napiš nám'; title_a = 'Napiš nám'; title_b = 'dopis.'; lede = 'Každou zprávu čte jedna osoba a odpoví do dvou pracovních dnů. Žádný ticketing systém. Žádný bot první linie. Žádné „váš hovor je pro nás důležitý". Vyber kanál níže — nebo pošli žádost o nástroj rovnou z formuláře.'; tab_message = 'Poslat zprávu'; tab_request = 'Vyžádat nástroj'; message_intro = 'Vrácení peněz, partnerství, bug reporty, nebo nám prostě říct, že jsme napsali manifest špatně — piš.'; request_intro = 'Roadmapa je otevřená. Řekni nám co bys chtěl vidět — jaký excel pořád lepíš lepenkou, jaký SaaS pořád rušíš a znovu předplácíš, jaký report stavíš ručně každé pondělí. Když 10 lidí požádá o totéž, postavíme to. Když jsi sám a je to chytré — postavíme to stejně.'; success_title = 'Zpráva přijata.'; success_body = 'Ozveme se do dvou pracovních dnů.'; request_success_title = 'Díky. Máme.'; request_success_body = 'Čteme každou žádost. Jestli ta tvoje pasuje do dílny, ozveme se.'; error_title = 'Nelze odeslat:'; direct_lines = 'Přímé kanály'; label_hello = 'Ahoj'; label_support = 'Podpora'; label_refund = 'Vrácení'; reply_window = 'Doba odpovědi'; reply_main = 'Odpovídáme po–pá do 2 pracovních dnů. Jedna reálná osoba, ne fronta.'; reply_mute = 'Všechny žádosti o nástroje čteme, ale odpovídáme jen když je stavíme nebo potřebujeme upřesnění.' }
  form = @{ name = 'Tvoje jméno'; email = 'Email'; subject = 'Předmět'; message = 'Zpráva'; category = 'Kategorie'; request_what = 'Jaký nástroj bys chtěl aby existoval?'; subject_placeholder = 'Vrácení · partnerství · bug · jiné'; request_placeholder = 'Čím kratší a podivnější, tím lepší.'; request_hint = 'Žádné NDA. Žádné kecy. Jen popiš co by ti ušetřilo nejvíc času.'; cat_crm = 'CRM a marketing'; cat_finance = 'Finance a trading'; cat_other = 'Produktivita / Jiné' }
  about = @{ eyebrow = 'O nás · založeno 2026'; title_a = 'Software, který si koupíš.'; title_b = 'Jednou.'; lede = 'Někde po cestě software sežral svět — a pak začal vybírat nájem za stopy po kousnutí. Každý workflow se stal předplatným. Každý nástroj se stal nájemníkem na tvém bankovním účtu. Každý operátor, marketér a trader začal platit 9, 29, 99 € měsíčně za privilegium dělat svou vlastní práci. Myslíme si, že je to divné.' }
  privacy = @{ eyebrow = 'Právní · Soukromí'; title_a = 'Tvoje data zůstávají'; title_b = 'na tvém disku.'; lede = 'Krátká verze: naše desktopové nástroje nevolají domů. Sbíráme jen absolutní minimum, které potřebujeme abychom ti prodali licenci, poslali odkaz ke stažení a vrátili peníze pokud požádáš. Nic víc.' }
  terms = @{ eyebrow = 'Právní · Podmínky'; title_a = 'Koupíš jednou. Tvoje'; title_b = 'navždy.'; lede = 'Lidsky: zaplatíš jednou, dostaneš trvalou licenci na používání aplikace na tvých strojích, zůstaneš s tím co jsi koupil i když zmizíme. Žádné předplatné, žádné automatické obnovení, žádné překvapivé blokace. Delší verze níže.' }
  refund = @{ eyebrow = 'Právní · Vrácení'; title_a = '30 dní.'; title_b = 'Bez otázek.'; lede = 'Pokud nástroj nesedí na tvůj workflow, nedělá co stránka slibovala, nebo sis to prostě rozmyslel — napiš nám do 30 dnů od koupě a vrátíme plnou částku. Žádné formuláře. Žádný exit interview. Žádný popup „jsi si jistý?".' }
  showcase = @{ eyebrow = 'Aktuálně k dispozici' }
}

$packs['sk'] = @{
  nav = @{ tools = 'Nástroje'; about = 'O nás'; request = 'Žiadosť'; contact = 'Kontakt' }
  cta = @{ get_a_tool = 'Kúpiť nástroj'; browse_tools = 'Prehliadať nástroje'; read_manifesto = 'Prečítať manifest'; send_message = 'Odoslať'; send_request = 'Odoslať žiadosť' }
  tagline = 'Raz kúpené. Tvoje navždy.'
  language_label = 'Jazyk'
  hero = @{ eyebrow = 'Weird Artist · založené 2026'; title_a = 'Softvér, ktorý si kúpiš.'; title_b = 'Raz.'; subtitle = 'Weird Artist vytvára desktopové nástroje pre marketérov, traderov a operátorov, ktorí odmietajú prenajímať si vlastný workflow.' }
  footer = @{ products = 'Produkty'; company = 'Firma'; legal = 'Právne'; blurb = 'Pay-once desktopové nástroje pre ľudí, ktorí prácu skutočne robia.'; upcoming = 'Čoskoro'; all_tools = 'Všetky nástroje'; request_a_tool = 'Vyžiadať nástroj'; privacy = 'Súkromie'; terms = 'Podmienky'; refund = 'Vrátenie' }
  contact = @{ eyebrow = 'Napíš nám'; title_a = 'Napíš nám'; title_b = 'list.'; lede = 'Každú správu číta jedna osoba a odpovie do dvoch pracovných dní. Žiadny ticket systém. Žiadny bot prvej línie. Žiadne „váš hovor je pre nás dôležitý". Vyber kanál nižšie — alebo pošli žiadosť o nástroj rovno z formulára.'; tab_message = 'Poslať správu'; tab_request = 'Vyžiadať nástroj'; message_intro = 'Vrátenie peňazí, partnerstvá, bug reporty, alebo nám len povedať, že sme napísali manifest zle — píš.'; request_intro = 'Roadmapa je otvorená. Povedz nám čo by si chcel vidieť — aký excel stále lepíš páskou, aký SaaS stále rušíš a znova predplatíš, aký report staviaš ručne každý pondelok. Ak 10 ľudí požiada o to isté, postavíme to. Ak si sám a je to chytré — postavíme to aj tak.'; success_title = 'Správa prijatá.'; success_body = 'Ozveme sa do dvoch pracovných dní.'; request_success_title = 'Vďaka. Máme.'; request_success_body = 'Čítame každú žiadosť. Ak tvoja pasuje do dielne, ozveme sa.'; error_title = 'Nepodarilo sa odoslať:'; direct_lines = 'Priame kanály'; label_hello = 'Ahoj'; label_support = 'Podpora'; label_refund = 'Vrátenie'; reply_window = 'Čas odpovede'; reply_main = 'Odpovedáme po–pi do 2 pracovných dní. Jedna reálna osoba, nie fronta.'; reply_mute = 'Všetky žiadosti o nástroje čítame, ale odpovedáme len keď ich staviame alebo potrebujeme upresnenie.' }
  form = @{ name = 'Tvoje meno'; email = 'Email'; subject = 'Predmet'; message = 'Správa'; category = 'Kategória'; request_what = 'Aký nástroj by si chcel aby existoval?'; subject_placeholder = 'Vrátenie · partnerstvo · bug · iné'; request_placeholder = 'Čím kratšie a divnejšie, tým lepšie.'; request_hint = 'Žiadne NDA. Žiadne kecy. Len opíš čo by ti ušetrilo najviac času.'; cat_crm = 'CRM a marketing'; cat_finance = 'Financie a trading'; cat_other = 'Produktivita / Iné' }
  about = @{ eyebrow = 'O nás · založené 2026'; title_a = 'Softvér, ktorý si kúpiš.'; title_b = 'Raz.'; lede = 'Niekde po ceste softvér zožral svet — a potom začal vyberať nájom za stopy po hryznutiach. Každý workflow sa stal predplatným. Každý nástroj sa stal nájomníkom na tvojom bankovom účte. Každý operátor, marketér a trader začal platiť 9, 29, 99 € mesačne za privilégium robiť svoju vlastnú prácu. Myslíme si, že je to divné.' }
  privacy = @{ eyebrow = 'Právne · Súkromie'; title_a = 'Tvoje dáta zostávajú'; title_b = 'na tvojom disku.'; lede = 'Krátka verzia: naše desktopové nástroje nevolajú domov. Zbierame iba absolútne minimum, ktoré potrebujeme aby sme ti predali licenciu, poslali link na stiahnutie a vrátili peniaze ak požiadaš. Nič viac.' }
  terms = @{ eyebrow = 'Právne · Podmienky'; title_a = 'Kúpiš raz. Tvoje'; title_b = 'navždy.'; lede = 'Po ľudsky: zaplatíš raz, dostaneš trvalú licenciu na používanie aplikácie na tvojich strojoch, zostaneš s tým čo si kúpil aj keď zmizneme. Žiadne predplatné, žiadne automatické obnovenie, žiadne prekvapivé blokácie. Dlhšia verzia nižšie.' }
  refund = @{ eyebrow = 'Právne · Vrátenie'; title_a = '30 dní.'; title_b = 'Bez otázok.'; lede = 'Ak nástroj nesedí na tvoj workflow, nerobí čo stránka sľubovala, alebo si si to jednoducho rozmyslel — napíš nám do 30 dní od kúpy a vrátime plnú sumu. Žiadne formuláre. Žiadny exit interview. Žiadny popup „si si istý?".' }
  showcase = @{ eyebrow = 'Aktuálne dostupné' }
}

$packs['es'] = @{
  nav = @{ tools = 'Herramientas'; about = 'Sobre nosotros'; request = 'Petición'; contact = 'Contacto' }
  cta = @{ get_a_tool = 'Comprar herramienta'; browse_tools = 'Ver herramientas'; read_manifesto = 'Leer el manifiesto'; send_message = 'Enviar'; send_request = 'Enviar petición' }
  tagline = 'Comprado una vez. Tuyo para siempre.'
  language_label = 'Idioma'
  hero = @{ eyebrow = 'Weird Artist · fundado en 2026'; title_a = 'Software que compras.'; title_b = 'Una vez.'; subtitle = 'Weird Artist hace herramientas de escritorio para marketers, traders y operadores que se niegan a alquilar su propio workflow.' }
  footer = @{ products = 'Productos'; company = 'Empresa'; legal = 'Legal'; blurb = 'Herramientas de escritorio de pago único para quienes realmente hacen el trabajo.'; upcoming = 'Próximamente'; all_tools = 'Todas las herramientas'; request_a_tool = 'Pedir una herramienta'; privacy = 'Privacidad'; terms = 'Términos'; refund = 'Reembolso' }
  contact = @{ eyebrow = 'Háblanos'; title_a = 'Escríbenos una'; title_b = 'carta.'; lede = 'Una sola persona lee cada mensaje y responde en dos días hábiles. Sin sistema de tickets. Sin bot de primera línea. Sin « su llamada es importante para nosotros ». Elige un canal abajo — o envía una petición de herramienta directamente desde el formulario.'; tab_message = 'Enviar mensaje'; tab_request = 'Pedir una herramienta'; message_intro = 'Reembolsos, partnerships, bug reports, o solo para decirnos que escribimos el manifiesto mal — escríbenos.'; request_intro = 'El roadmap está abierto. Dinos qué te gustaría ver — qué hoja de cálculo sigues remendando, qué SaaS sigues cancelando y resuscribiendo, qué reporte construyes a mano cada lunes. Si 10 personas piden lo mismo, lo construimos. Si eres tú solo y es ingenioso — lo construimos igual.'; success_title = 'Mensaje recibido.'; success_body = 'Te responderemos en dos días hábiles.'; request_success_title = 'Gracias. Recibido.'; request_success_body = 'Leemos cada petición. Si la tuya encaja en el taller, te responderemos.'; error_title = 'No se pudo enviar:'; direct_lines = 'Líneas directas'; label_hello = 'Hola'; label_support = 'Soporte'; label_refund = 'Reembolso'; reply_window = 'Tiempo de respuesta'; reply_main = 'Respondemos lun–vie en 2 días hábiles. Una persona real, no una cola.'; reply_mute = 'Leemos todas las peticiones de herramientas pero solo respondemos si la construimos o necesitamos aclaración.' }
  form = @{ name = 'Tu nombre'; email = 'Email'; subject = 'Asunto'; message = 'Mensaje'; category = 'Categoría'; request_what = '¿Qué herramienta te gustaría que existiera?'; subject_placeholder = 'Reembolso · partnership · bug · otro'; request_placeholder = 'Cuanto más corto y raro, mejor.'; request_hint = 'Sin NDA. Sin paja. Solo describe lo que te ahorraría más tiempo.'; cat_crm = 'CRM y Marketing'; cat_finance = 'Finanzas y Trading'; cat_other = 'Productividad / Otro' }
  about = @{ eyebrow = 'Sobre nosotros · fundado en 2026'; title_a = 'Software que compras.'; title_b = 'Una vez.'; lede = 'En algún momento del camino el software se comió el mundo — y después empezó a cobrar alquiler por las marcas de mordisco. Cada workflow se convirtió en una suscripción. Cada herramienta se convirtió en un inquilino en tu cuenta bancaria. Cada operador, marketer y trader empezó a pagar 9, 29, 99 € al mes por el privilegio de hacer su propio trabajo. Nos parece raro.' }
  privacy = @{ eyebrow = 'Legal · Privacidad'; title_a = 'Tus datos se quedan'; title_b = 'en tu disco.'; lede = 'Versión corta: nuestras herramientas de escritorio no llaman a casa. Recogemos lo mínimo necesario para venderte una licencia, enviarte el enlace de descarga y devolverte el dinero si lo pides. Nada más.' }
  terms = @{ eyebrow = 'Legal · Términos'; title_a = 'Compras una vez. Tuyo'; title_b = 'para siempre.'; lede = 'En cristiano: pagas una vez, recibes una licencia perpetua para usar la app en tus máquinas, te quedas con lo que compraste incluso si desaparecemos. Sin suscripción, sin renovación automática, sin bloqueos sorpresa. La versión larga abajo.' }
  refund = @{ eyebrow = 'Legal · Reembolso'; title_a = '30 días.'; title_b = 'Sin preguntas.'; lede = 'Si la herramienta no encaja en tu workflow, no hace lo que la página prometía, o simplemente cambiaste de opinión — escríbenos en 30 días desde la compra y reembolsamos el importe completo. Sin formularios. Sin exit interview. Sin popup « ¿estás seguro? ».' }
  showcase = @{ eyebrow = 'Disponible ahora' }
}

$packs['ru'] = @{
  nav = @{ tools = 'Инструменты'; about = 'О нас'; request = 'Запрос'; contact = 'Контакты' }
  cta = @{ get_a_tool = 'Купить инструмент'; browse_tools = 'Каталог'; read_manifesto = 'Манифест'; send_message = 'Отправить'; send_request = 'Отправить запрос' }
  tagline = 'Куплено раз. Твоё навсегда.'
  language_label = 'Язык'
  hero = @{ eyebrow = 'Weird Artist · основано 2026'; title_a = 'Софт, который покупаешь.'; title_b = 'Один раз.'; subtitle = 'Weird Artist делает десктоп-инструменты для маркетологов, трейдеров и операционщиков, которые не хотят арендовать собственный рабочий процесс.' }
  footer = @{ products = 'Продукты'; company = 'Компания'; legal = 'Правовая информация'; blurb = 'Pay-once десктоп-инструменты для тех, кто реально делает работу.'; upcoming = 'Скоро'; all_tools = 'Все инструменты'; request_a_tool = 'Запрос на инструмент'; privacy = 'Конфиденциальность'; terms = 'Условия'; refund = 'Возврат' }
  contact = @{ eyebrow = 'Напиши нам'; title_a = 'Напиши нам'; title_b = 'письмо.'; lede = 'Каждое сообщение читает один человек и отвечает в течение двух рабочих дней. Никаких тикет-систем. Никаких ботов первой линии. Никаких «ваш звонок важен для нас». Выбери канал ниже — или отправь запрос на инструмент сразу через форму.'; tab_message = 'Отправить сообщение'; tab_request = 'Запросить инструмент'; message_intro = 'Возвраты, партнёрства, баги, или просто сказать что мы написали манифест неправильно — пиши.'; request_intro = 'Roadmap открыт. Расскажи что хотел бы увидеть — какую таблицу ты постоянно склеиваешь скотчем, какой SaaS ты постоянно отменяешь и подписываешь снова, какой отчёт ты каждый понедельник делаешь руками. Если 10 человек попросят одно и то же, мы построим. Если ты один и идея крутая — построим всё равно.'; success_title = 'Сообщение получено.'; success_body = 'Ответим в течение двух рабочих дней.'; request_success_title = 'Спасибо. Получили.'; request_success_body = 'Читаем каждый запрос. Если твой подходит мастерской — ответим.'; error_title = 'Не удалось отправить:'; direct_lines = 'Прямые контакты'; label_hello = 'Привет'; label_support = 'Поддержка'; label_refund = 'Возврат'; reply_window = 'Время ответа'; reply_main = 'Отвечаем пн–пт в течение 2 рабочих дней. Один живой человек, а не очередь.'; reply_mute = 'Запросы на инструменты читаем все, но отвечаем только если беремся строить или нужно уточнение.' }
  form = @{ name = 'Твоё имя'; email = 'Email'; subject = 'Тема'; message = 'Сообщение'; category = 'Категория'; request_what = 'Какой инструмент ты хотел бы видеть?'; subject_placeholder = 'Возврат · партнёрство · баг · другое'; request_placeholder = 'Чем короче и страннее — тем лучше.'; request_hint = 'Без NDA. Без воды. Просто опиши что сэкономило бы тебе больше всего времени.'; cat_crm = 'CRM и маркетинг'; cat_finance = 'Финансы и трейдинг'; cat_other = 'Продуктивность / Другое' }
  about = @{ eyebrow = 'О нас · основано 2026'; title_a = 'Софт, который покупаешь.'; title_b = 'Один раз.'; lede = 'Где-то по дороге софт съел мир — а потом начал брать ренту за следы укусов. Каждый рабочий процесс превратился в подписку. Каждый инструмент стал арендатором в твоём банковском счёте. Каждый оператор, маркетолог и трейдер начал платить $9, $29, $99 в месяц за привилегию делать свою собственную работу. Мы считаем это странным.' }
  privacy = @{ eyebrow = 'Правовая · Приватность'; title_a = 'Твои данные остаются'; title_b = 'на твоём диске.'; lede = 'Коротко: наши десктоп-инструменты не звонят домой. Мы собираем минимум, нужный чтобы продать тебе лицензию, отправить ссылку на скачивание и вернуть деньги если попросишь. И всё.' }
  terms = @{ eyebrow = 'Правовая · Условия'; title_a = 'Покупаешь раз. Твоё'; title_b = 'навсегда.'; lede = 'По-человечески: платишь один раз, получаешь бессрочную лицензию на использование приложения на своих машинах, остаёшься с тем что купил даже если мы исчезнем. Никаких подписок, никакого авто-продления, никаких сюрпризных блокировок. Расширенная версия ниже.' }
  refund = @{ eyebrow = 'Правовая · Возврат'; title_a = '30 дней.'; title_b = 'Без вопросов.'; lede = 'Если инструмент не подошёл твоему процессу, не делает того что обещала страница, или ты просто передумал — напиши нам в течение 30 дней с покупки и мы вернём полную сумму. Никаких форм. Никакого exit interview. Никакого попапа «ты уверен?».' }
  showcase = @{ eyebrow = 'Сейчас в магазине' }
}

# ============================================================
# EXTRA PACKS — namespaces for /pages/tools, /pages/crm-marketing,
# /pages/finance-trading, /pages/promptgrid and the 404 page.
# Merged into $packs above before the MERGE step.
# ============================================================

$extraPacks = @{}

$extraPacks['en.default'] = @{
  tools_hub = @{ eyebrow = 'Two universes, one workshop'; title_a = 'Pick your'; title_b = 'workshop.'; lede = 'Two categories. Both desktop. Both pay-once. Both shipping in 2026.'; crm_title = 'CRM &amp; Marketing'; crm_desc = 'Email builders, segmentation helpers, campaign exporters — for the people who actually press send.'; crm_count = '1 tool · 1 in alpha'; fin_title = 'Finance &amp; Trading'; fin_desc = 'Local P/L analyzers, exchange CSV crunchers, journal tools — for traders who don&rsquo;t want their broker to know.'; fin_count = '1 tool · coming Q3'; view_tools = 'View tools'; foot = 'Want a third category? '; foot_link = 'Tell us what you wish existed.' }
  cat = @{ workshop = 'In the workshop'; alpha = 'Closed alpha'; coming = 'Coming Q3 2026'; back = 'Back to all categories'; cta_alpha = 'Request alpha access'; cta_waitlist = 'Join the waitlist'; cta_manifesto = 'Read the manifesto'; crm_eyebrow = 'Category · CRM &amp; Marketing'; crm_title_a = 'For the people who'; crm_title_b = 'press send.'; crm_lede = 'Desktop tools for marketers and CRM operators who got tired of paying $99/month to copy-paste the same email into the same dashboard. Mass editors, exporters, two-way syncs — local-first.'; crm_showcase_a = 'One tool'; crm_showcase_b = 'shipping in alpha.'; crm_pg_tag = 'Mass HTML email &amp; push editor for Customer.io operators.'; crm_pg_desc = 'A desktop CRM workbench for marketers who run hundreds of campaigns across regions and locales. Edit emails, push, in-app and surveys with WYSIWYG and CodeMirror side-by-side. Pull and push to Customer.io US/EU. ZIP an entire project. Version everything locally — no cloud, no telemetry, no per-seat tax.'; crm_pg_f1 = 'Multi-project storage with deep copy &amp; bulk ops'; crm_pg_f2 = 'Customer.io two-way sync (US &amp; EU regions)'; crm_pg_f3 = 'WYSIWYG + HTML mode with syntax highlighting'; crm_pg_f4 = 'Locale-aware editing across emails, push, in-app, surveys'; crm_pg_f5 = 'Project ZIP archive · full history journal · Ukrainian UI'; fin_eyebrow = 'Category · Finance &amp; Trading'; fin_title_a = 'For traders who don&rsquo;t want'; fin_title_b = 'their broker to know.'; fin_lede = 'Local-first analyzers and journals for crypto, futures, and spot. Crunch your CSVs on your machine. Your numbers never leave the desk.'; fin_showcase_a = 'One tool'; fin_showcase_b = 'shipping in 2026.'; fin_ba_tag = 'Local P/L analyzer for Binance Spot, Futures USD-M and COIN-M.'; fin_ba_desc = 'A desktop journal that reads your raw Binance CSV exports and turns them into an honest P/L view: realized, unrealized, fees, funding, by symbol, by month. Local files only — your trade history stays on your disk.'; fin_ba_f1 = 'Spot · Futures USD-M · Futures COIN-M imports'; fin_ba_f2 = 'Per-symbol &amp; per-month P/L breakdown'; fin_ba_f3 = 'Funding, fees and rebates accounted separately'; fin_ba_f4 = 'CSV in, CSV out — no API key needed, no cloud sync'; fin_ba_f5 = 'Multi-account aggregation with per-wallet filters' }
  notfound = @{ eyebrow = 'Lost in the workshop'; title_a = 'This page'; title_b = 'never shipped.'; lede = 'The link is wrong, the page was deleted, or we never built it. Either way — let&rsquo;s get you back to something useful.'; cta_home = 'Back to home'; cta_contact = 'Tell us what broke'; shortcut_tools_key = 'Browse'; shortcut_about_key = 'Read'; shortcut_request_key = 'Ask'; shortcut_contact_key = 'Talk' }
  pg = @{ eyebrow = 'PromptGrid · CRM workbench'; title_a = 'Mass-edit campaigns'; title_b = 'on your own machine.'; lede = 'A desktop workbench for marketers who ship hundreds of emails, push, in-app and surveys across locales — without paying per seat or trusting a cloud editor.'; badge = 'Closed alpha'; tag = 'Mass HTML email &amp; push editor for Customer.io operators.'; desc = 'Edit emails, push, in-app and surveys with WYSIWYG and CodeMirror side-by-side. Pull and push to Customer.io US/EU. ZIP an entire project. Version everything locally — no cloud, no telemetry, no per-seat tax.'; f1 = 'Multi-project storage with deep copy &amp; bulk ops'; f2 = 'Customer.io two-way sync (US &amp; EU regions)'; f3 = 'WYSIWYG + HTML mode with syntax highlighting'; f4 = 'Locale-aware editing across emails, push, in-app, surveys'; f5 = 'Project ZIP archive · full history journal · Ukrainian UI'; cta_alpha = 'Request alpha access'; cta_more = 'See category' }
}

$extraPacks['uk'] = @{
  tools_hub = @{ eyebrow = 'Два світи · одна майстерня'; title_a = 'Обери свою'; title_b = 'майстерню.'; lede = 'Дві категорії. Обидві десктопні. Обидві pay-once. Обидві виходять у 2026.'; crm_title = 'CRM і маркетинг'; crm_desc = 'Білдери листів, інструменти сегментації, експортери кампаній — для тих, хто реально натискає Send.'; crm_count = '1 інструмент · 1 в альфі'; fin_title = 'Фінанси і трейдинг'; fin_desc = 'Локальні P/L-аналізатори, CSV-кранчери для бірж, журнали трейдів — для тих, хто не хоче щоб брокер усе бачив.'; fin_count = '1 інструмент · скоро Q3'; view_tools = 'Переглянути'; foot = 'Хочеш третю категорію? '; foot_link = 'Розкажи що ти хотів би побачити.' }
  cat = @{ workshop = 'У майстерні'; alpha = 'Закрита альфа'; coming = 'Скоро Q3 2026'; back = 'Назад до категорій'; cta_alpha = 'Доступ до альфи'; cta_waitlist = 'У список очікування'; cta_manifesto = 'Маніфест'; crm_eyebrow = 'Категорія · CRM і маркетинг'; crm_title_a = 'Для тих, хто'; crm_title_b = 'натискає Send.'; crm_lede = 'Десктоп-інструменти для маркетологів і CRM-операційників, які втомились платити $99/місяць щоб копіпастити той самий лист у ту саму панель. Масові редактори, експортери, двосторонні синки — local-first.'; crm_showcase_a = 'Один інструмент'; crm_showcase_b = 'у закритій альфі.'; crm_pg_tag = 'Масовий редактор HTML-листів і пушів для операторів Customer.io.'; crm_pg_desc = 'Десктоп-майстерня для маркетологів, які ведуть сотні кампаній по регіонах і мовах. Редагуєш листи, пуші, in-app і опитування — WYSIWYG і CodeMirror поряд. Pull/push у Customer.io US/EU. ZIP усього проєкту. Версіонування локально — без хмари, без телеметрії, без оренди за seat.'; crm_pg_f1 = 'Зберігання кількох проєктів з deep-copy і bulk-операціями'; crm_pg_f2 = 'Двосторонній синк з Customer.io (US і EU)'; crm_pg_f3 = 'WYSIWYG + HTML-режим з підсвіткою синтаксису'; crm_pg_f4 = 'Багатомовне редагування листів, пушів, in-app, опитувань'; crm_pg_f5 = 'ZIP-архів проєкту · повний журнал змін · український UI'; fin_eyebrow = 'Категорія · Фінанси і трейдинг'; fin_title_a = 'Для трейдерів, які не хочуть'; fin_title_b = 'щоб брокер бачив.'; fin_lede = 'Локальні аналізатори і журнали для крипти, ф&apos;ючерсів і споту. Кранчиш CSV у себе на машині. Числа не виходять зі столу.'; fin_showcase_a = 'Один інструмент'; fin_showcase_b = 'виходить у 2026.'; fin_ba_tag = 'Локальний P/L-аналізатор для Binance Spot, Futures USD-M і COIN-M.'; fin_ba_desc = 'Десктоп-журнал, який читає сирі CSV-експорти Binance і перетворює їх на чесний P/L: реалізований, нереалізований, комісії, фандинг, по символах, по місяцях. Тільки локальні файли — історія трейдів лишається на твоєму диску.'; fin_ba_f1 = 'Імпорти Spot · Futures USD-M · Futures COIN-M'; fin_ba_f2 = 'Розбивка P/L по символах і місяцях'; fin_ba_f3 = 'Фандинг, комісії і рібейти окремо'; fin_ba_f4 = 'CSV in, CSV out — без API-ключів, без хмари'; fin_ba_f5 = 'Агрегація кількох акаунтів з фільтрами по гаманцях' }
  notfound = @{ eyebrow = 'Загубився у майстерні'; title_a = 'Цю сторінку'; title_b = 'так і не випустили.'; lede = 'Лінк неправильний, сторінку видалили, або ми її ніколи не будували. У будь-якому разі — повертаймо тебе до чогось корисного.'; cta_home = 'На головну'; cta_contact = 'Розкажи що зламалось'; shortcut_tools_key = 'Каталог'; shortcut_about_key = 'Прочитати'; shortcut_request_key = 'Запитати'; shortcut_contact_key = 'Поговорити' }
  pg = @{ eyebrow = 'PromptGrid · CRM-майстерня'; title_a = 'Масово редагуй кампанії'; title_b = 'на власній машині.'; lede = 'Десктоп-майстерня для маркетологів, які випускають сотні листів, пушів, in-app і опитувань між мовами — без оренди за seat і без хмарного редактора.'; badge = 'Закрита альфа'; tag = 'Масовий редактор HTML-листів і пушів для операторів Customer.io.'; desc = 'Редагуєш листи, пуші, in-app і опитування — WYSIWYG і CodeMirror поряд. Pull/push у Customer.io US/EU. ZIP усього проєкту. Версіонування локально — без хмари, без телеметрії, без оренди за seat.'; f1 = 'Зберігання кількох проєктів з deep-copy і bulk-операціями'; f2 = 'Двосторонній синк з Customer.io (US і EU)'; f3 = 'WYSIWYG + HTML-режим з підсвіткою синтаксису'; f4 = 'Багатомовне редагування листів, пушів, in-app, опитувань'; f5 = 'ZIP-архів проєкту · повний журнал змін · український UI'; cta_alpha = 'Доступ до альфи'; cta_more = 'Дивитись категорію' }
}

$extraPacks['de'] = @{
  tools_hub = @{ eyebrow = 'Zwei Welten · eine Werkstatt'; title_a = 'Wähle deine'; title_b = 'Werkstatt.'; lede = 'Zwei Kategorien. Beide Desktop. Beide pay-once. Beide erscheinen 2026.'; crm_title = 'CRM &amp; Marketing'; crm_desc = 'E-Mail-Builder, Segmentierungshelfer, Kampagnen-Exporter — für Leute, die wirklich auf Senden drücken.'; crm_count = '1 Tool · 1 in Alpha'; fin_title = 'Finance &amp; Trading'; fin_desc = 'Lokale P/L-Analyzer, Exchange-CSV-Cruncher, Trade-Journale — für Trader, die nicht wollen, dass ihr Broker mitliest.'; fin_count = '1 Tool · Q3 in Arbeit'; view_tools = 'Tools ansehen'; foot = 'Eine dritte Kategorie gewünscht? '; foot_link = 'Sag uns, was dir fehlt.' }
  cat = @{ workshop = 'In der Werkstatt'; alpha = 'Geschlossene Alpha'; coming = 'Q3 2026'; back = 'Zurück zu allen Kategorien'; cta_alpha = 'Alpha-Zugang anfragen'; cta_waitlist = 'Auf die Warteliste'; cta_manifesto = 'Manifest lesen'; crm_eyebrow = 'Kategorie · CRM &amp; Marketing'; crm_title_a = 'Für die, die wirklich'; crm_title_b = 'auf Senden drücken.'; crm_lede = 'Desktop-Tools für Marketer und CRM-Operatoren, die genug davon haben, $99/Monat zu zahlen, um dieselbe E-Mail in dasselbe Dashboard zu kopieren. Massen-Editoren, Exporter, Two-Way-Syncs — local-first.'; crm_showcase_a = 'Ein Tool'; crm_showcase_b = 'in Alpha.'; crm_pg_tag = 'Massen-HTML-E-Mail- und Push-Editor für Customer.io-Operatoren.'; crm_pg_desc = 'Eine Desktop-CRM-Werkstatt für Marketer, die hunderte Kampagnen über Regionen und Sprachen hinweg fahren. WYSIWYG und CodeMirror nebeneinander. Pull und Push zu Customer.io US/EU. Ganzes Projekt als ZIP. Versionierung lokal — keine Cloud, keine Telemetrie, keine Seat-Gebühr.'; crm_pg_f1 = 'Multi-Projekt-Speicher mit Deep-Copy und Bulk-Ops'; crm_pg_f2 = 'Customer.io Two-Way-Sync (US &amp; EU)'; crm_pg_f3 = 'WYSIWYG + HTML-Modus mit Syntax-Highlighting'; crm_pg_f4 = 'Sprachbewusstes Bearbeiten von E-Mails, Push, In-App, Umfragen'; crm_pg_f5 = 'Projekt-ZIP · vollständiger Verlauf · UI auf Ukrainisch'; fin_eyebrow = 'Kategorie · Finance &amp; Trading'; fin_title_a = 'Für Trader, die nicht wollen,'; fin_title_b = 'dass der Broker mitliest.'; fin_lede = 'Lokale Analyzer und Journale für Crypto, Futures und Spot. CSVs auf deiner Maschine. Deine Zahlen verlassen den Schreibtisch nicht.'; fin_showcase_a = 'Ein Tool'; fin_showcase_b = 'erscheint 2026.'; fin_ba_tag = 'Lokaler P/L-Analyzer für Binance Spot, Futures USD-M und COIN-M.'; fin_ba_desc = 'Ein Desktop-Journal, das deine rohen Binance-CSV-Exporte in eine ehrliche P/L-Sicht verwandelt: realisiert, unrealisiert, Gebühren, Funding, pro Symbol, pro Monat. Nur lokale Dateien — deine Trade-Historie bleibt auf deiner Festplatte.'; fin_ba_f1 = 'Imports: Spot · Futures USD-M · Futures COIN-M'; fin_ba_f2 = 'P/L pro Symbol und pro Monat'; fin_ba_f3 = 'Funding, Gebühren und Rebates separat geführt'; fin_ba_f4 = 'CSV rein, CSV raus — kein API-Key, keine Cloud'; fin_ba_f5 = 'Multi-Account-Aggregation mit Wallet-Filtern' }
  notfound = @{ eyebrow = 'In der Werkstatt verloren'; title_a = 'Diese Seite'; title_b = 'wurde nie ausgeliefert.'; lede = 'Der Link ist falsch, die Seite wurde gelöscht, oder wir haben sie nie gebaut. Wie auch immer — bringen wir dich zurück zu etwas Brauchbarem.'; cta_home = 'Zur Startseite'; cta_contact = 'Sag uns was kaputt ist'; shortcut_tools_key = 'Stöbern'; shortcut_about_key = 'Lesen'; shortcut_request_key = 'Fragen'; shortcut_contact_key = 'Reden' }
  pg = @{ eyebrow = 'PromptGrid · CRM-Werkstatt'; title_a = 'Kampagnen massenhaft bearbeiten'; title_b = 'auf deinem eigenen Rechner.'; lede = 'Eine Desktop-Werkstatt für Marketer, die hunderte E-Mails, Push, In-App und Umfragen über Sprachen hinweg ausliefern — ohne Pro-Seat-Gebühr und ohne Cloud-Editor.'; badge = 'Geschlossene Alpha'; tag = 'Massen-HTML-E-Mail- und Push-Editor für Customer.io-Operatoren.'; desc = 'WYSIWYG und CodeMirror nebeneinander. Pull und Push zu Customer.io US/EU. Ganzes Projekt als ZIP. Versionierung lokal — keine Cloud, keine Telemetrie, keine Seat-Gebühr.'; f1 = 'Multi-Projekt-Speicher mit Deep-Copy und Bulk-Ops'; f2 = 'Customer.io Two-Way-Sync (US &amp; EU)'; f3 = 'WYSIWYG + HTML-Modus mit Syntax-Highlighting'; f4 = 'Sprachbewusstes Bearbeiten von E-Mails, Push, In-App, Umfragen'; f5 = 'Projekt-ZIP · vollständiger Verlauf · UI auf Ukrainisch'; cta_alpha = 'Alpha-Zugang anfragen'; cta_more = 'Kategorie ansehen' }
}

$extraPacks['fr'] = @{
  tools_hub = @{ eyebrow = 'Deux univers · un atelier'; title_a = 'Choisis ton'; title_b = 'atelier.'; lede = 'Deux catégories. Toutes desktop. Toutes pay-once. Toutes prévues pour 2026.'; crm_title = 'CRM &amp; Marketing'; crm_desc = 'Éditeurs d&rsquo;e-mails, aides à la segmentation, exporteurs de campagnes — pour ceux qui appuient vraiment sur Envoyer.'; crm_count = '1 outil · 1 en alpha'; fin_title = 'Finance &amp; Trading'; fin_desc = 'Analyseurs P/L locaux, parseurs CSV d&rsquo;exchanges, journaux de trade — pour les traders qui ne veulent pas que leur broker sache.'; fin_count = '1 outil · prévu Q3'; view_tools = 'Voir les outils'; foot = 'Tu veux une troisième catégorie ? '; foot_link = 'Dis-nous ce qui te manque.' }
  cat = @{ workshop = 'À l&rsquo;atelier'; alpha = 'Alpha fermée'; coming = 'Q3 2026'; back = 'Retour aux catégories'; cta_alpha = 'Demander l&rsquo;accès alpha'; cta_waitlist = 'Rejoindre la liste'; cta_manifesto = 'Lire le manifeste'; crm_eyebrow = 'Catégorie · CRM &amp; Marketing'; crm_title_a = 'Pour ceux qui'; crm_title_b = 'appuient sur Envoyer.'; crm_lede = 'Outils desktop pour les marketers et opérateurs CRM fatigués de payer 99 $/mois pour copier-coller le même e-mail dans le même dashboard. Éditeurs en masse, exporteurs, syncs bidirectionnels — local-first.'; crm_showcase_a = 'Un outil'; crm_showcase_b = 'en alpha.'; crm_pg_tag = 'Éditeur d&rsquo;e-mails HTML et push en masse pour les opérateurs Customer.io.'; crm_pg_desc = 'Un atelier CRM desktop pour les marketers qui pilotent des centaines de campagnes à travers les régions et les langues. WYSIWYG et CodeMirror côte à côte. Pull et push vers Customer.io US/EU. Tout le projet en ZIP. Versionnement local — pas de cloud, pas de télémétrie, pas de tarif par siège.'; crm_pg_f1 = 'Stockage multi-projets avec deep-copy et opérations en masse'; crm_pg_f2 = 'Sync bidirectionnel Customer.io (US &amp; EU)'; crm_pg_f3 = 'Mode WYSIWYG + HTML avec coloration syntaxique'; crm_pg_f4 = 'Édition multilingue : e-mails, push, in-app, sondages'; crm_pg_f5 = 'Archive ZIP du projet · journal complet · UI ukrainien'; fin_eyebrow = 'Catégorie · Finance &amp; Trading'; fin_title_a = 'Pour les traders qui ne veulent pas que'; fin_title_b = 'leur broker sache.'; fin_lede = 'Analyseurs et journaux locaux pour crypto, futures et spot. Tu crunches tes CSV chez toi. Tes chiffres ne quittent pas le bureau.'; fin_showcase_a = 'Un outil'; fin_showcase_b = 'prévu pour 2026.'; fin_ba_tag = 'Analyseur P/L local pour Binance Spot, Futures USD-M et COIN-M.'; fin_ba_desc = 'Un journal desktop qui lit tes exports CSV bruts de Binance et les transforme en P/L honnête : réalisé, non réalisé, frais, funding, par symbole, par mois. Fichiers locaux uniquement — ton historique reste sur ton disque.'; fin_ba_f1 = 'Imports : Spot · Futures USD-M · Futures COIN-M'; fin_ba_f2 = 'P/L par symbole et par mois'; fin_ba_f3 = 'Funding, frais et rebates comptés séparément'; fin_ba_f4 = 'CSV en entrée, CSV en sortie — pas d&rsquo;API key, pas de cloud'; fin_ba_f5 = 'Agrégation multi-comptes avec filtres par wallet' }
  notfound = @{ eyebrow = 'Perdu dans l&rsquo;atelier'; title_a = 'Cette page'; title_b = 'n&rsquo;a jamais été livrée.'; lede = 'Le lien est faux, la page a été supprimée, ou on ne l&rsquo;a jamais construite. Dans tous les cas — ramenons-toi vers quelque chose d&rsquo;utile.'; cta_home = 'Retour à l&rsquo;accueil'; cta_contact = 'Dis-nous ce qui ne va pas'; shortcut_tools_key = 'Parcourir'; shortcut_about_key = 'Lire'; shortcut_request_key = 'Demander'; shortcut_contact_key = 'Parler' }
  pg = @{ eyebrow = 'PromptGrid · atelier CRM'; title_a = 'Éditer les campagnes en masse'; title_b = 'sur ta propre machine.'; lede = 'Un atelier desktop pour les marketers qui livrent des centaines d&rsquo;e-mails, push, in-app et sondages multilingues — sans payer par siège et sans confier à un éditeur cloud.'; badge = 'Alpha fermée'; tag = 'Éditeur d&rsquo;e-mails HTML et push en masse pour les opérateurs Customer.io.'; desc = 'WYSIWYG et CodeMirror côte à côte. Pull et push vers Customer.io US/EU. Tout le projet en ZIP. Versionnement local — pas de cloud, pas de télémétrie, pas de tarif par siège.'; f1 = 'Stockage multi-projets avec deep-copy et opérations en masse'; f2 = 'Sync bidirectionnel Customer.io (US &amp; EU)'; f3 = 'Mode WYSIWYG + HTML avec coloration syntaxique'; f4 = 'Édition multilingue : e-mails, push, in-app, sondages'; f5 = 'Archive ZIP du projet · journal complet · UI ukrainien'; cta_alpha = 'Demander l&rsquo;accès alpha'; cta_more = 'Voir la catégorie' }
}

$extraPacks['it'] = @{
  tools_hub = @{ eyebrow = 'Due universi · un&rsquo;officina'; title_a = 'Scegli la tua'; title_b = 'officina.'; lede = 'Due categorie. Entrambe desktop. Entrambe pay-once. Entrambe in arrivo nel 2026.'; crm_title = 'CRM &amp; Marketing'; crm_desc = 'Editor di e-mail, helper di segmentazione, esportatori di campagne — per chi davvero preme Invia.'; crm_count = '1 strumento · 1 in alpha'; fin_title = 'Finance &amp; Trading'; fin_desc = 'Analizzatori P/L locali, parser di CSV degli exchange, journal di trade — per trader che non vogliono che il broker sappia.'; fin_count = '1 strumento · in arrivo Q3'; view_tools = 'Vedi gli strumenti'; foot = 'Vuoi una terza categoria? '; foot_link = 'Dicci cosa ti manca.' }
  cat = @{ workshop = 'In officina'; alpha = 'Alpha chiusa'; coming = 'Q3 2026'; back = 'Torna a tutte le categorie'; cta_alpha = 'Richiedi accesso alpha'; cta_waitlist = 'Lista d&rsquo;attesa'; cta_manifesto = 'Leggi il manifesto'; crm_eyebrow = 'Categoria · CRM &amp; Marketing'; crm_title_a = 'Per chi davvero'; crm_title_b = 'preme Invia.'; crm_lede = 'Strumenti desktop per marketer e operatori CRM stanchi di pagare 99 $/mese per copia-incollare la stessa e-mail nello stesso dashboard. Editor di massa, esportatori, sync bidirezionali — local-first.'; crm_showcase_a = 'Uno strumento'; crm_showcase_b = 'in alpha.'; crm_pg_tag = 'Editor di e-mail HTML e push di massa per operatori Customer.io.'; crm_pg_desc = 'Un&rsquo;officina CRM desktop per marketer che gestiscono centinaia di campagne tra regioni e lingue. WYSIWYG e CodeMirror affiancati. Pull e push a Customer.io US/EU. Intero progetto in ZIP. Versioning locale — niente cloud, niente telemetria, niente costo per postazione.'; crm_pg_f1 = 'Storage multi-progetto con deep-copy e operazioni di massa'; crm_pg_f2 = 'Sync bidirezionale Customer.io (US &amp; EU)'; crm_pg_f3 = 'Modalità WYSIWYG + HTML con syntax highlighting'; crm_pg_f4 = 'Editing multilingua: e-mail, push, in-app, sondaggi'; crm_pg_f5 = 'Archivio ZIP del progetto · log completo · UI in ucraino'; fin_eyebrow = 'Categoria · Finance &amp; Trading'; fin_title_a = 'Per i trader che non vogliono'; fin_title_b = 'che il broker sappia.'; fin_lede = 'Analizzatori e journal locali per crypto, futures e spot. CSV processati sul tuo computer. I tuoi numeri non lasciano la scrivania.'; fin_showcase_a = 'Uno strumento'; fin_showcase_b = 'in arrivo nel 2026.'; fin_ba_tag = 'Analizzatore P/L locale per Binance Spot, Futures USD-M e COIN-M.'; fin_ba_desc = 'Un journal desktop che legge i tuoi export CSV grezzi di Binance e li trasforma in un P/L onesto: realizzato, non realizzato, fee, funding, per simbolo, per mese. Solo file locali — la tua trade history resta sul tuo disco.'; fin_ba_f1 = 'Import: Spot · Futures USD-M · Futures COIN-M'; fin_ba_f2 = 'P/L per simbolo e per mese'; fin_ba_f3 = 'Funding, fee e rebate contati separatamente'; fin_ba_f4 = 'CSV in, CSV out — nessuna API key, nessun cloud'; fin_ba_f5 = 'Aggregazione multi-account con filtri per wallet' }
  notfound = @{ eyebrow = 'Perso in officina'; title_a = 'Questa pagina'; title_b = 'non è mai stata rilasciata.'; lede = 'Il link è sbagliato, la pagina è stata cancellata, o non l&rsquo;abbiamo mai costruita. In ogni caso — riportiamoti su qualcosa di utile.'; cta_home = 'Torna alla home'; cta_contact = 'Dicci cosa è rotto'; shortcut_tools_key = 'Sfoglia'; shortcut_about_key = 'Leggi'; shortcut_request_key = 'Chiedi'; shortcut_contact_key = 'Parla' }
  pg = @{ eyebrow = 'PromptGrid · officina CRM'; title_a = 'Modifica le campagne in massa'; title_b = 'sulla tua macchina.'; lede = 'Un&rsquo;officina desktop per marketer che spediscono centinaia di e-mail, push, in-app e sondaggi multilingua — senza pagare per postazione e senza affidarsi a un editor cloud.'; badge = 'Alpha chiusa'; tag = 'Editor di e-mail HTML e push di massa per operatori Customer.io.'; desc = 'WYSIWYG e CodeMirror affiancati. Pull e push a Customer.io US/EU. Intero progetto in ZIP. Versioning locale — niente cloud, niente telemetria, niente costo per postazione.'; f1 = 'Storage multi-progetto con deep-copy e operazioni di massa'; f2 = 'Sync bidirezionale Customer.io (US &amp; EU)'; f3 = 'Modalità WYSIWYG + HTML con syntax highlighting'; f4 = 'Editing multilingua: e-mail, push, in-app, sondaggi'; f5 = 'Archivio ZIP del progetto · log completo · UI in ucraino'; cta_alpha = 'Richiedi accesso alpha'; cta_more = 'Vedi categoria' }
}

$extraPacks['pl'] = @{
  tools_hub = @{ eyebrow = 'Dwa światy · jeden warsztat'; title_a = 'Wybierz swój'; title_b = 'warsztat.'; lede = 'Dwie kategorie. Obie desktopowe. Obie pay-once. Obie wychodzą w 2026.'; crm_title = 'CRM i marketing'; crm_desc = 'Edytory maili, helpery do segmentacji, eksportery kampanii — dla tych, którzy naprawdę naciskają Wyślij.'; crm_count = '1 narzędzie · 1 w alpha'; fin_title = 'Finanse i trading'; fin_desc = 'Lokalne analizatory P/L, crunchery CSV z giełd, journale tradingowe — dla traderów, którzy nie chcą, żeby broker wiedział.'; fin_count = '1 narzędzie · planowane Q3'; view_tools = 'Zobacz narzędzia'; foot = 'Chcesz trzecią kategorię? '; foot_link = 'Powiedz nam, czego brakuje.' }
  cat = @{ workshop = 'W warsztacie'; alpha = 'Zamknięta alpha'; coming = 'Q3 2026'; back = 'Wróć do kategorii'; cta_alpha = 'Poproś o dostęp alpha'; cta_waitlist = 'Lista oczekujących'; cta_manifesto = 'Przeczytaj manifest'; crm_eyebrow = 'Kategoria · CRM i marketing'; crm_title_a = 'Dla tych, którzy naprawdę'; crm_title_b = 'naciskają Wyślij.'; crm_lede = 'Desktopowe narzędzia dla marketerów i operatorów CRM zmęczonych płaceniem 99 $/miesiąc za kopiowanie tego samego maila do tego samego dashboardu. Edytory masowe, eksportery, dwukierunkowe synki — local-first.'; crm_showcase_a = 'Jedno narzędzie'; crm_showcase_b = 'w alphie.'; crm_pg_tag = 'Masowy edytor maili HTML i pushów dla operatorów Customer.io.'; crm_pg_desc = 'Desktopowy warsztat CRM dla marketerów prowadzących setki kampanii w różnych regionach i językach. WYSIWYG i CodeMirror obok siebie. Pull i push do Customer.io US/EU. Cały projekt w ZIP. Wersjonowanie lokalnie — bez chmury, bez telemetrii, bez opłaty per stanowisko.'; crm_pg_f1 = 'Wieloprojektowy storage z deep-copy i operacjami masowymi'; crm_pg_f2 = 'Dwukierunkowy sync z Customer.io (US i EU)'; crm_pg_f3 = 'Tryb WYSIWYG + HTML z podświetlaniem składni'; crm_pg_f4 = 'Edycja wielojęzyczna: maile, push, in-app, ankiety'; crm_pg_f5 = 'Archiwum ZIP projektu · pełny log zmian · UI po ukraińsku'; fin_eyebrow = 'Kategoria · Finanse i trading'; fin_title_a = 'Dla traderów, którzy nie chcą,'; fin_title_b = 'żeby broker widział.'; fin_lede = 'Lokalne analizatory i journale dla krypto, futures i spotu. CSV przetwarzasz na swojej maszynie. Twoje liczby nie opuszczają biurka.'; fin_showcase_a = 'Jedno narzędzie'; fin_showcase_b = 'wychodzi w 2026.'; fin_ba_tag = 'Lokalny analizator P/L dla Binance Spot, Futures USD-M i COIN-M.'; fin_ba_desc = 'Desktopowy journal, który czyta surowe eksporty CSV z Binance i zamienia je w uczciwy widok P/L: zrealizowany, niezrealizowany, prowizje, funding, na symbol, na miesiąc. Tylko pliki lokalne — twoja historia transakcji zostaje na dysku.'; fin_ba_f1 = 'Importy: Spot · Futures USD-M · Futures COIN-M'; fin_ba_f2 = 'P/L na symbol i na miesiąc'; fin_ba_f3 = 'Funding, prowizje i rabaty liczone osobno'; fin_ba_f4 = 'CSV in, CSV out — bez API key, bez chmury'; fin_ba_f5 = 'Agregacja wielu kont z filtrami per portfel' }
  notfound = @{ eyebrow = 'Zgubiłeś się w warsztacie'; title_a = 'Ta strona'; title_b = 'nigdy nie została wydana.'; lede = 'Link jest błędny, strona została usunięta, albo nigdy jej nie zbudowaliśmy. Tak czy inaczej — wracajmy do czegoś użytecznego.'; cta_home = 'Na stronę główną'; cta_contact = 'Powiedz nam, co się zepsuło'; shortcut_tools_key = 'Przeglądaj'; shortcut_about_key = 'Czytaj'; shortcut_request_key = 'Zapytaj'; shortcut_contact_key = 'Porozmawiaj' }
  pg = @{ eyebrow = 'PromptGrid · warsztat CRM'; title_a = 'Edytuj kampanie masowo'; title_b = 'na własnej maszynie.'; lede = 'Desktopowy warsztat dla marketerów wysyłających setki maili, pushów, in-app i ankiet w wielu językach — bez opłaty per stanowisko i bez powierzania chmurowemu edytorowi.'; badge = 'Zamknięta alpha'; tag = 'Masowy edytor maili HTML i pushów dla operatorów Customer.io.'; desc = 'WYSIWYG i CodeMirror obok siebie. Pull i push do Customer.io US/EU. Cały projekt w ZIP. Wersjonowanie lokalnie — bez chmury, bez telemetrii, bez opłaty per stanowisko.'; f1 = 'Wieloprojektowy storage z deep-copy i operacjami masowymi'; f2 = 'Dwukierunkowy sync z Customer.io (US i EU)'; f3 = 'Tryb WYSIWYG + HTML z podświetlaniem składni'; f4 = 'Edycja wielojęzyczna: maile, push, in-app, ankiety'; f5 = 'Archiwum ZIP projektu · pełny log zmian · UI po ukraińsku'; cta_alpha = 'Poproś o dostęp alpha'; cta_more = 'Zobacz kategorię' }
}

$extraPacks['cs'] = @{
  tools_hub = @{ eyebrow = 'Dva světy · jedna dílna'; title_a = 'Vyber si svou'; title_b = 'dílnu.'; lede = 'Dvě kategorie. Obě desktopové. Obě pay-once. Obě vyjdou v 2026.'; crm_title = 'CRM a marketing'; crm_desc = 'Editory e-mailů, pomocníky pro segmentaci, exportéry kampaní — pro ty, kdo opravdu mačkají Odeslat.'; crm_count = '1 nástroj · 1 v alpha'; fin_title = 'Finance a trading'; fin_desc = 'Lokální P/L analyzátory, parsery CSV z burz, deníky obchodů — pro tradery, kteří nechtějí, aby broker věděl.'; fin_count = '1 nástroj · plánováno Q3'; view_tools = 'Zobrazit nástroje'; foot = 'Chceš třetí kategorii? '; foot_link = 'Řekni nám, co ti chybí.' }
  cat = @{ workshop = 'V dílně'; alpha = 'Uzavřená alpha'; coming = 'Q3 2026'; back = 'Zpět na všechny kategorie'; cta_alpha = 'Požádat o alpha přístup'; cta_waitlist = 'Na waitlist'; cta_manifesto = 'Přečíst manifest'; crm_eyebrow = 'Kategorie · CRM a marketing'; crm_title_a = 'Pro ty, kdo opravdu'; crm_title_b = 'mačkají Odeslat.'; crm_lede = 'Desktopové nástroje pro markeťáky a CRM operátory unavené z placení 99 $/měsíc za kopírování stejného e-mailu do stejného dashboardu. Hromadné editory, exportéry, obousměrné synky — local-first.'; crm_showcase_a = 'Jeden nástroj'; crm_showcase_b = 'v alphě.'; crm_pg_tag = 'Hromadný editor HTML e-mailů a push notifikací pro operátory Customer.io.'; crm_pg_desc = 'Desktopová CRM dílna pro markeťáky, kteří vedou stovky kampaní napříč regiony a jazyky. WYSIWYG a CodeMirror vedle sebe. Pull a push do Customer.io US/EU. Celý projekt jako ZIP. Verzování lokálně — žádný cloud, žádná telemetrie, žádný poplatek za sedadlo.'; crm_pg_f1 = 'Multi-projektové úložiště s deep-copy a hromadnými operacemi'; crm_pg_f2 = 'Obousměrný sync s Customer.io (US a EU)'; crm_pg_f3 = 'Režim WYSIWYG + HTML se zvýrazněním syntaxe'; crm_pg_f4 = 'Vícejazyčná editace: e-maily, push, in-app, ankety'; crm_pg_f5 = 'ZIP archiv projektu · plný log změn · UI v ukrajinštině'; fin_eyebrow = 'Kategorie · Finance a trading'; fin_title_a = 'Pro tradery, kteří nechtějí,'; fin_title_b = 'aby broker viděl.'; fin_lede = 'Lokální analyzátory a deníky pro krypto, futures a spot. CSV crunchneš na svém počítači. Tvá čísla neopustí stůl.'; fin_showcase_a = 'Jeden nástroj'; fin_showcase_b = 'vyjde v 2026.'; fin_ba_tag = 'Lokální P/L analyzátor pro Binance Spot, Futures USD-M a COIN-M.'; fin_ba_desc = 'Desktopový deník, který čte surové CSV exporty z Binance a převádí je na poctivý P/L: realizovaný, nerealizovaný, poplatky, funding, podle symbolu, podle měsíce. Pouze lokální soubory — tvá historie obchodů zůstává na disku.'; fin_ba_f1 = 'Importy: Spot · Futures USD-M · Futures COIN-M'; fin_ba_f2 = 'P/L podle symbolu a podle měsíce'; fin_ba_f3 = 'Funding, poplatky a rebaty počítány zvlášť'; fin_ba_f4 = 'CSV dovnitř, CSV ven — bez API key, bez cloudu'; fin_ba_f5 = 'Agregace více účtů s filtry podle peněženky' }
  notfound = @{ eyebrow = 'Ztracený v dílně'; title_a = 'Tahle stránka'; title_b = 'se nikdy nedodala.'; lede = 'Odkaz je špatný, stránka byla smazaná, nebo jsme ji nikdy nepostavili. Tak či tak — vrátíme tě k něčemu užitečnému.'; cta_home = 'Na hlavní stránku'; cta_contact = 'Řekni nám, co je rozbité'; shortcut_tools_key = 'Procházet'; shortcut_about_key = 'Číst'; shortcut_request_key = 'Zeptat se'; shortcut_contact_key = 'Mluvit' }
  pg = @{ eyebrow = 'PromptGrid · CRM dílna'; title_a = 'Edituj kampaně hromadně'; title_b = 'na vlastním stroji.'; lede = 'Desktopová dílna pro markeťáky, kteří posílají stovky e-mailů, push, in-app a anket napříč jazyky — bez poplatku za sedadlo a bez svěření cloudovému editoru.'; badge = 'Uzavřená alpha'; tag = 'Hromadný editor HTML e-mailů a push notifikací pro operátory Customer.io.'; desc = 'WYSIWYG a CodeMirror vedle sebe. Pull a push do Customer.io US/EU. Celý projekt jako ZIP. Verzování lokálně — žádný cloud, žádná telemetrie, žádný poplatek za sedadlo.'; f1 = 'Multi-projektové úložiště s deep-copy a hromadnými operacemi'; f2 = 'Obousměrný sync s Customer.io (US a EU)'; f3 = 'Režim WYSIWYG + HTML se zvýrazněním syntaxe'; f4 = 'Vícejazyčná editace: e-maily, push, in-app, ankety'; f5 = 'ZIP archiv projektu · plný log změn · UI v ukrajinštině'; cta_alpha = 'Požádat o alpha přístup'; cta_more = 'Zobrazit kategorii' }
}

$extraPacks['sk'] = @{
  tools_hub = @{ eyebrow = 'Dva svety · jedna dielňa'; title_a = 'Vyber si svoju'; title_b = 'dielňu.'; lede = 'Dve kategórie. Obe desktopové. Obe pay-once. Obe vyjdú v 2026.'; crm_title = 'CRM a marketing'; crm_desc = 'Editory e-mailov, pomocníci pre segmentáciu, exportéry kampaní — pre tých, čo skutočne stláčajú Odoslať.'; crm_count = '1 nástroj · 1 v alpha'; fin_title = 'Financie a trading'; fin_desc = 'Lokálne P/L analyzátory, parsery CSV z búrz, denníky obchodov — pre traderov, ktorí nechcú, aby broker vedel.'; fin_count = '1 nástroj · plánované Q3'; view_tools = 'Zobraziť nástroje'; foot = 'Chceš tretiu kategóriu? '; foot_link = 'Povedz nám, čo ti chýba.' }
  cat = @{ workshop = 'V dielni'; alpha = 'Uzavretá alpha'; coming = 'Q3 2026'; back = 'Späť na všetky kategórie'; cta_alpha = 'Požiadať o alpha prístup'; cta_waitlist = 'Na waitlist'; cta_manifesto = 'Prečítať manifest'; crm_eyebrow = 'Kategória · CRM a marketing'; crm_title_a = 'Pre tých, čo skutočne'; crm_title_b = 'stláčajú Odoslať.'; crm_lede = 'Desktopové nástroje pre marketérov a CRM operátorov unavených z platenia 99 $/mesiac za kopírovanie toho istého e-mailu do toho istého dashboardu. Hromadné editory, exportéry, obojsmerné synky — local-first.'; crm_showcase_a = 'Jeden nástroj'; crm_showcase_b = 'v alphe.'; crm_pg_tag = 'Hromadný editor HTML e-mailov a push notifikácií pre operátorov Customer.io.'; crm_pg_desc = 'Desktopová CRM dielňa pre marketérov, ktorí vedú stovky kampaní naprieč regiónmi a jazykmi. WYSIWYG a CodeMirror vedľa seba. Pull a push do Customer.io US/EU. Celý projekt ako ZIP. Verzovanie lokálne — žiadny cloud, žiadna telemetria, žiadny poplatok za miesto.'; crm_pg_f1 = 'Multi-projektové úložisko s deep-copy a hromadnými operáciami'; crm_pg_f2 = 'Obojsmerný sync s Customer.io (US a EU)'; crm_pg_f3 = 'Režim WYSIWYG + HTML so zvýrazňovaním syntaxe'; crm_pg_f4 = 'Viacjazyčná editácia: e-maily, push, in-app, ankety'; crm_pg_f5 = 'ZIP archív projektu · plný log zmien · UI v ukrajinčine'; fin_eyebrow = 'Kategória · Financie a trading'; fin_title_a = 'Pre traderov, ktorí nechcú,'; fin_title_b = 'aby broker videl.'; fin_lede = 'Lokálne analyzátory a denníky pre krypto, futures a spot. CSV cruchneš na svojom počítači. Tvoje čísla neopustia stôl.'; fin_showcase_a = 'Jeden nástroj'; fin_showcase_b = 'vyjde v 2026.'; fin_ba_tag = 'Lokálny P/L analyzátor pre Binance Spot, Futures USD-M a COIN-M.'; fin_ba_desc = 'Desktopový denník, ktorý číta surové CSV exporty z Binance a mení ich na poctivý P/L: realizovaný, nerealizovaný, poplatky, funding, podľa symbolu, podľa mesiaca. Iba lokálne súbory — tvoja história obchodov zostáva na disku.'; fin_ba_f1 = 'Importy: Spot · Futures USD-M · Futures COIN-M'; fin_ba_f2 = 'P/L podľa symbolu a podľa mesiaca'; fin_ba_f3 = 'Funding, poplatky a rebaty počítané zvlášť'; fin_ba_f4 = 'CSV dnu, CSV von — bez API key, bez cloudu'; fin_ba_f5 = 'Agregácia viacerých účtov s filtrami podľa peňaženky' }
  notfound = @{ eyebrow = 'Stratený v dielni'; title_a = 'Táto stránka'; title_b = 'nebola nikdy vydaná.'; lede = 'Odkaz je zlý, stránka bola zmazaná, alebo sme ju nikdy nepostavili. Tak či tak — vrátime ťa k niečomu užitočnému.'; cta_home = 'Na hlavnú stránku'; cta_contact = 'Povedz nám, čo je pokazené'; shortcut_tools_key = 'Prehliadať'; shortcut_about_key = 'Čítať'; shortcut_request_key = 'Spýtať sa'; shortcut_contact_key = 'Hovoriť' }
  pg = @{ eyebrow = 'PromptGrid · CRM dielňa'; title_a = 'Edituj kampane hromadne'; title_b = 'na vlastnom stroji.'; lede = 'Desktopová dielňa pre marketérov, ktorí posielajú stovky e-mailov, push, in-app a ankiet naprieč jazykmi — bez poplatku za miesto a bez zverenia cloudovému editoru.'; badge = 'Uzavretá alpha'; tag = 'Hromadný editor HTML e-mailov a push notifikácií pre operátorov Customer.io.'; desc = 'WYSIWYG a CodeMirror vedľa seba. Pull a push do Customer.io US/EU. Celý projekt ako ZIP. Verzovanie lokálne — žiadny cloud, žiadna telemetria, žiadny poplatok za miesto.'; f1 = 'Multi-projektové úložisko s deep-copy a hromadnými operáciami'; f2 = 'Obojsmerný sync s Customer.io (US a EU)'; f3 = 'Režim WYSIWYG + HTML so zvýrazňovaním syntaxe'; f4 = 'Viacjazyčná editácia: e-maily, push, in-app, ankety'; f5 = 'ZIP archív projektu · plný log zmien · UI v ukrajinčine'; cta_alpha = 'Požiadať o alpha prístup'; cta_more = 'Zobraziť kategóriu' }
}

$extraPacks['es'] = @{
  tools_hub = @{ eyebrow = 'Dos universos · un taller'; title_a = 'Elige tu'; title_b = 'taller.'; lede = 'Dos categorías. Las dos desktop. Las dos pay-once. Las dos llegan en 2026.'; crm_title = 'CRM y marketing'; crm_desc = 'Editores de correo, helpers de segmentación, exportadores de campañas — para los que de verdad pulsan Enviar.'; crm_count = '1 herramienta · 1 en alpha'; fin_title = 'Finanzas y trading'; fin_desc = 'Analizadores P/L locales, parsers de CSV de exchanges, journals de trading — para traders que no quieren que su bróker lo sepa.'; fin_count = '1 herramienta · llega Q3'; view_tools = 'Ver herramientas'; foot = '¿Quieres una tercera categoría? '; foot_link = 'Cuéntanos qué te falta.' }
  cat = @{ workshop = 'En el taller'; alpha = 'Alpha cerrada'; coming = 'Q3 2026'; back = 'Volver a todas las categorías'; cta_alpha = 'Pedir acceso alpha'; cta_waitlist = 'Lista de espera'; cta_manifesto = 'Leer el manifiesto'; crm_eyebrow = 'Categoría · CRM y marketing'; crm_title_a = 'Para los que de verdad'; crm_title_b = 'pulsan Enviar.'; crm_lede = 'Herramientas desktop para marketers y operadores CRM cansados de pagar 99 $/mes por copiar y pegar el mismo correo en el mismo dashboard. Editores masivos, exportadores, syncs bidireccionales — local-first.'; crm_showcase_a = 'Una herramienta'; crm_showcase_b = 'en alpha.'; crm_pg_tag = 'Editor masivo de correos HTML y push para operadores de Customer.io.'; crm_pg_desc = 'Un taller CRM desktop para marketers que llevan cientos de campañas entre regiones e idiomas. WYSIWYG y CodeMirror lado a lado. Pull y push a Customer.io US/EU. Todo el proyecto en ZIP. Versionado en local — sin nube, sin telemetría, sin coste por asiento.'; crm_pg_f1 = 'Almacenamiento multiproyecto con deep-copy y operaciones masivas'; crm_pg_f2 = 'Sync bidireccional con Customer.io (US y EU)'; crm_pg_f3 = 'Modo WYSIWYG + HTML con resaltado de sintaxis'; crm_pg_f4 = 'Edición multilingüe: correos, push, in-app, encuestas'; crm_pg_f5 = 'Archivo ZIP del proyecto · log completo · UI en ucraniano'; fin_eyebrow = 'Categoría · Finanzas y trading'; fin_title_a = 'Para traders que no quieren'; fin_title_b = 'que su bróker lo sepa.'; fin_lede = 'Analizadores y journals locales para crypto, futuros y spot. Procesas tus CSV en tu máquina. Tus números no salen del escritorio.'; fin_showcase_a = 'Una herramienta'; fin_showcase_b = 'llega en 2026.'; fin_ba_tag = 'Analizador P/L local para Binance Spot, Futures USD-M y COIN-M.'; fin_ba_desc = 'Un journal desktop que lee tus exports CSV en bruto de Binance y los convierte en un P/L honesto: realizado, no realizado, comisiones, funding, por símbolo, por mes. Solo archivos locales — tu historial de trading se queda en tu disco.'; fin_ba_f1 = 'Imports: Spot · Futures USD-M · Futures COIN-M'; fin_ba_f2 = 'P/L por símbolo y por mes'; fin_ba_f3 = 'Funding, comisiones y rebates contados aparte'; fin_ba_f4 = 'CSV dentro, CSV fuera — sin API key, sin nube'; fin_ba_f5 = 'Agregación multi-cuenta con filtros por wallet' }
  notfound = @{ eyebrow = 'Perdido en el taller'; title_a = 'Esta página'; title_b = 'nunca llegó a salir.'; lede = 'El enlace está mal, la página se borró, o nunca la construimos. Sea como sea — te llevamos de vuelta a algo útil.'; cta_home = 'Volver al inicio'; cta_contact = 'Cuéntanos qué falló'; shortcut_tools_key = 'Explorar'; shortcut_about_key = 'Leer'; shortcut_request_key = 'Preguntar'; shortcut_contact_key = 'Hablar' }
  pg = @{ eyebrow = 'PromptGrid · taller CRM'; title_a = 'Edita campañas en masa'; title_b = 'en tu propia máquina.'; lede = 'Un taller desktop para marketers que envían cientos de correos, push, in-app y encuestas en varios idiomas — sin pagar por asiento y sin confiar en un editor en la nube.'; badge = 'Alpha cerrada'; tag = 'Editor masivo de correos HTML y push para operadores de Customer.io.'; desc = 'WYSIWYG y CodeMirror lado a lado. Pull y push a Customer.io US/EU. Todo el proyecto en ZIP. Versionado en local — sin nube, sin telemetría, sin coste por asiento.'; f1 = 'Almacenamiento multiproyecto con deep-copy y operaciones masivas'; f2 = 'Sync bidireccional con Customer.io (US y EU)'; f3 = 'Modo WYSIWYG + HTML con resaltado de sintaxis'; f4 = 'Edición multilingüe: correos, push, in-app, encuestas'; f5 = 'Archivo ZIP del proyecto · log completo · UI en ucraniano'; cta_alpha = 'Pedir acceso alpha'; cta_more = 'Ver categoría' }
}

$extraPacks['ru'] = @{
  tools_hub = @{ eyebrow = 'Две вселенные · одна мастерская'; title_a = 'Выбери свою'; title_b = 'мастерскую.'; lede = 'Две категории. Обе десктопные. Обе pay-once. Обе выходят в 2026.'; crm_title = 'CRM и маркетинг'; crm_desc = 'Билдеры писем, инструменты сегментации, экспортёры кампаний — для тех, кто реально жмёт Send.'; crm_count = '1 инструмент · 1 в альфе'; fin_title = 'Финансы и трейдинг'; fin_desc = 'Локальные P/L-анализаторы, кранчеры CSV для бирж, журналы трейдов — для тех, кто не хочет, чтобы брокер всё видел.'; fin_count = '1 инструмент · скоро Q3'; view_tools = 'Посмотреть'; foot = 'Хочешь третью категорию? '; foot_link = 'Расскажи, чего тебе не хватает.' }
  cat = @{ workshop = 'В мастерской'; alpha = 'Закрытая альфа'; coming = 'Скоро Q3 2026'; back = 'Назад к категориям'; cta_alpha = 'Доступ к альфе'; cta_waitlist = 'В лист ожидания'; cta_manifesto = 'Манифест'; crm_eyebrow = 'Категория · CRM и маркетинг'; crm_title_a = 'Для тех, кто'; crm_title_b = 'жмёт Send.'; crm_lede = 'Десктоп-инструменты для маркетологов и CRM-операторов, уставших платить $99/месяц за то, чтобы копипастить одно и то же письмо в одну и ту же панель. Массовые редакторы, экспортёры, двусторонние синки — local-first.'; crm_showcase_a = 'Один инструмент'; crm_showcase_b = 'в закрытой альфе.'; crm_pg_tag = 'Массовый редактор HTML-писем и пушей для операторов Customer.io.'; crm_pg_desc = 'Десктоп-мастерская для маркетологов, которые ведут сотни кампаний по регионам и языкам. WYSIWYG и CodeMirror рядом. Pull/push в Customer.io US/EU. ZIP всего проекта. Версионирование локально — без облака, без телеметрии, без аренды за seat.'; crm_pg_f1 = 'Хранение нескольких проектов с deep-copy и bulk-операциями'; crm_pg_f2 = 'Двусторонний синк с Customer.io (US и EU)'; crm_pg_f3 = 'WYSIWYG + HTML-режим с подсветкой синтаксиса'; crm_pg_f4 = 'Многоязычное редактирование писем, пушей, in-app, опросов'; crm_pg_f5 = 'ZIP-архив проекта · полный журнал изменений · украинский UI'; fin_eyebrow = 'Категория · Финансы и трейдинг'; fin_title_a = 'Для трейдеров, которые не хотят,'; fin_title_b = 'чтобы брокер видел.'; fin_lede = 'Локальные анализаторы и журналы для крипты, фьючерсов и спота. Кранчишь CSV у себя на машине. Цифры не покидают стол.'; fin_showcase_a = 'Один инструмент'; fin_showcase_b = 'выходит в 2026.'; fin_ba_tag = 'Локальный P/L-анализатор для Binance Spot, Futures USD-M и COIN-M.'; fin_ba_desc = 'Десктоп-журнал, который читает сырые CSV-экспорты Binance и превращает их в честный P/L: реализованный, нереализованный, комиссии, фандинг, по символам, по месяцам. Только локальные файлы — история трейдов остаётся на твоём диске.'; fin_ba_f1 = 'Импорты: Spot · Futures USD-M · Futures COIN-M'; fin_ba_f2 = 'Разбивка P/L по символам и месяцам'; fin_ba_f3 = 'Фандинг, комиссии и ребейты отдельно'; fin_ba_f4 = 'CSV in, CSV out — без API-ключей, без облака'; fin_ba_f5 = 'Агрегация нескольких аккаунтов с фильтрами по кошелькам' }
  notfound = @{ eyebrow = 'Потерялся в мастерской'; title_a = 'Эту страницу'; title_b = 'так и не выпустили.'; lede = 'Ссылка неверная, страницу удалили, или мы её никогда не строили. В любом случае — вернём тебя к чему-то полезному.'; cta_home = 'На главную'; cta_contact = 'Расскажи, что сломалось'; shortcut_tools_key = 'Каталог'; shortcut_about_key = 'Прочитать'; shortcut_request_key = 'Спросить'; shortcut_contact_key = 'Поговорить' }
  pg = @{ eyebrow = 'PromptGrid · CRM-мастерская'; title_a = 'Массово редактируй кампании'; title_b = 'на собственной машине.'; lede = 'Десктоп-мастерская для маркетологов, выпускающих сотни писем, пушей, in-app и опросов между языками — без аренды за seat и без облачного редактора.'; badge = 'Закрытая альфа'; tag = 'Массовый редактор HTML-писем и пушей для операторов Customer.io.'; desc = 'WYSIWYG и CodeMirror рядом. Pull/push в Customer.io US/EU. ZIP всего проекта. Версионирование локально — без облака, без телеметрии, без аренды за seat.'; f1 = 'Хранение нескольких проектов с deep-copy и bulk-операциями'; f2 = 'Двусторонний синк с Customer.io (US и EU)'; f3 = 'WYSIWYG + HTML-режим с подсветкой синтаксиса'; f4 = 'Многоязычное редактирование писем, пушей, in-app, опросов'; f5 = 'ZIP-архив проекта · полный журнал изменений · украинский UI'; cta_alpha = 'Доступ к альфе'; cta_more = 'Смотреть категорию' }
}

# Merge $extraPacks into $packs (adds new namespaces alongside existing)
foreach ($key in $extraPacks.Keys) {
  if (-not $packs.ContainsKey($key)) { continue }
  foreach ($ns in $extraPacks[$key].Keys) {
    $packs[$key][$ns] = $extraPacks[$key][$ns]
  }
}

# ============================================================
# MERGE
# ============================================================
foreach ($key in $packs.Keys) {
  $file = Join-Path $localesDir "$key.json"
  if (-not (Test-Path $file)) {
    Write-Host "SKIP $key — file not found: $file" -ForegroundColor Yellow
    continue
  }
  $text = [System.IO.File]::ReadAllText($file, $enc)
  $cleaned = Remove-ExistingWa -text $text
  $waJson = Build-WaBlock -wa $packs[$key]
  $merged = Insert-Wa -text $cleaned -waJson $waJson
  [System.IO.File]::WriteAllText($file, $merged, $enc)
  Write-Host "OK   $key" -ForegroundColor Green
}

Write-Host ""
Write-Host "Done. Run: shopify theme push --only locales/" -ForegroundColor Cyan
